#!/usr/bin/env node
// Offline, deterministic bundling of licensed MP3 recordings into the single-file app.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'audio/manifest.json'),'utf8'));
const {kana}=JSON.parse(fs.readFileSync(path.join(root,'data/kana-basic.v1.json'),'utf8'));
const ids=kana.filter(k=>k.kind==='basic').map(k=>k.id);
assert.equal(manifest.clips.length,44);
assert.deepEqual(manifest.clips.map(c=>c.kanaId),ids);
const sha=(b,algo='sha256')=>crypto.createHash(algo).update(b).digest('hex');
const clips={};
for(const c of manifest.clips){
  assert.equal(c.author,'Hakatanoshio117117');
  assert.equal(c.license,'Public domain (PD-self)');
  assert.ok(c.sourcePage.startsWith('https://commons.wikimedia.org/wiki/File:'));
  assert.ok(c.sourceDescription.includes(kana.find(k=>k.id===c.kanaId).hiragana),`Wrong source sound: ${c.kanaId}`);
  const original=fs.readFileSync(path.join(root,c.originalPath));
  assert.equal(sha(original,'sha1'),c.sourceSha1,`Changed source: ${c.kanaId}`);
  const bytes=fs.readFileSync(path.join(root,c.mp3Path));
  assert.equal(sha(bytes),c.mp3Sha256,`Changed MP3: ${c.kanaId}`);
  assert.ok(bytes.length>1000 && bytes.length<100000);
  clips[c.kanaId]='data:audio/mpeg;base64,'+bytes.toString('base64');
}
const bundle={schemaVersion:1,audioVersion:'1.0.0',author:manifest.author,license:manifest.license,
  collectionUrl:manifest.collectionUrl,clips};
const js='// Generated by kana-rebuild/tools/build-audio.cjs; public-domain human recordings.\n'+
  '// Per-file source/author/licence/hashes: kana-rebuild/audio/manifest.json.\n'+
  'globalThis.KANA_REBUILD_AUDIO = '+JSON.stringify(bundle).replace(/</g,'\\u003c')+';\n';
fs.mkdirSync(path.join(root,'generated'),{recursive:true});
fs.writeFileSync(path.join(root,'generated/kana-audio.js'),js);
console.log(`PASS: ${ids.length} human recordings bundled offline (${Buffer.byteLength(js)} bytes).`);
