#!/usr/bin/env node
// 把 oral-audio/<batch>/ 的逐句 MP3（正常＋慢速）包成 data URI，給單檔 index.html 離線播放（鎖屏聽力播放器 src/lockplay.js）。
// 用法：node oral-audio/tools/build-embed.cjs [batch01]   （build.sh 會自動跑）
// 只讀 manifest.json 與 mp3/，檢查 sha256 後輸出 oral-audio/generated/<batch>-audio.js。連播檔 batch01_playlist.mp3 不打包（太大，另外附）。
const fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto'), assert = require('node:assert/strict');
const HERE = path.resolve(__dirname, '..'), batch = process.argv[2] || 'batch01';
const dir = path.join(HERE, batch), m = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8'));
assert.equal(m.batch, batch);
const sha = b => crypto.createHash('sha256').update(b).digest('hex');
let raw = 0;
const items = m.items.map(it => {
  const a = {};
  for (const k of ['normal', 'slow']) {
    const x = it.audio[k], b = fs.readFileSync(path.join(dir, x.file));
    assert.equal(sha(b), x.sha256, `Changed MP3: ${x.file}`);
    assert.ok(b.length > 1000 && b.length < 200000, `Odd size: ${x.file}`);
    raw += b.length; a[k] = 'data:audio/mpeg;base64,' + b.toString('base64'); a[k + 'Sec'] = x.durationSeconds;
  }
  return {n:it.n, id:it.id, ja:it.ja, jaRuby:it.jaRuby, kana:it.kana, romaji:it.romaji, zh:it.zh, who:it.speaker,
    task:it.source.taskName || '', chunks:it.chunks, ...a};
});
const bundle = {schemaVersion:1, batch, title:m.title, synthetic:!!m.synthetic,
  credit:`合成語音：Open JTalk＋HTS Voice "Mei"（${m.engine.voiceLicense}）`, items};
const js = `// Generated by oral-audio/tools/build-embed.cjs from oral-audio/${batch}/manifest.json — do not edit.\n` +
  '// Synthetic speech; attribution: oral-audio/ATTRIBUTION.md\n' +
  'globalThis.ORAL_AUDIO = ' + JSON.stringify(bundle).replace(/</g, '\\u003c') + ';\n';
fs.mkdirSync(path.join(HERE, 'generated'), {recursive:true});
fs.writeFileSync(path.join(HERE, 'generated', batch + '-audio.js'), js);
console.log(`PASS: ${items.length} sentences × 2 speeds bundled (${raw} MP3 bytes → ${Buffer.byteLength(js)} bytes JS).`);
