// First-version anchors are editorial selections. IDs are explicit and must not be renumbered.
// Native word spelling is preserved; reading, rather than surface spelling, determines the kana bucket.
const W = (id, word, reading, romaji, meaningZh, note = '') => ({id, word, reading, romaji, meaningZh, note});
const words = [
  W('arigatou','ありがとう','ありがとう','arigatou','謝謝'),
  W('asa','朝','あさ','asa','早上'),
  W('ikitai','行きたい','いきたい','ikitai','想去','從現有「行きたいです」取出；保留想去的形式，不改成另一個動詞。'),
  W('iie','いいえ','いいえ','iie','不／不是'),
  W('ue','上','うえ','ue','上面'),
  W('umi','海','うみ','umi','海'),
  W('eki','駅','えき','eki','車站'),
  W('eiga','映画','えいが','eiga','電影'),
  W('okaikei','お会計','おかいけい','okaikei','結帳'),
  W('omoi','重い','おもい','omoi','重的','卡片保留常見漢字寫法與讀音。'),
  W('kankou','観光','かんこう','kankou','觀光'),
  W('kaimono','買い物','かいもの','kaimono','購物'),
  W('kippu','切符','きっぷ','kippu','車票','單字裡的 っ 先聽整詞，不要求第一版另外考促音。'),
  W('kita','北','きた','kita','北邊'),
  W('kudasai','ください','ください','kudasai','請給我／請……'),
  W('kutsu','靴','くつ','kutsu','鞋子'),
  W('keitai','携帯','けいたい','keitai','手機'),
  W('kekkou','結構です','けっこうです','kekkou desu','不用了，謝謝','這個補充例子的中文只用於婉拒情境；結構也可表示「很好／足夠」，不能當成唯一詞義。'),
  W('kore','これ','これ','kore','這個'),
  W('koko','ここ','ここ','koko','這裡'),
  W('sake','酒','さけ','sake','酒'),
  W('sakana','魚','さかな','sakana','魚'),
  W('shigoto','仕事','しごと','shigoto','工作'),
  W('shio','塩','しお','shio','鹽'),
  W('sumimasen','すみません','すみません','sumimasen','不好意思'),
  W('suki','好き','すき','suki','喜歡'),
  W('sentakuki','洗濯機','せんたくき','sentakuki','洗衣機'),
  W('seki','席','せき','seki','座位'),
  W('sore','それ','それ','sore','那個'),
  W('soto','外','そと','soto','外面'),
  W('taiwan','台湾','たいわん','taiwan','台灣'),
  W('taberu','食べる','たべる','taberu','吃'),
  W('chizu','地図','ちず','chizu','地圖'),
  W('chikatetsu','地下鉄','ちかてつ','chikatetsu','地下鐵'),
  W('tsugi','次','つぎ','tsugi','下一個／下一班'),
  W('tsumetai','冷たい','つめたい','tsumetai','冰涼的／冷的'),
  W('te','手','て','te','手'),
  W('tenki','天気','てんき','tenki','天氣'),
  W('tomarimasu','泊まります','とまります','tomarimasu','住宿／過夜','「泊まる」是住宿；不要和同音的「止まる」混成一個意思。'),
  W('tomodachi','友達','ともだち','tomodachi','朋友'),
  W('namae','名前','なまえ','namae','名字'),
  W('nani','何','なに','nani','什麼','此處選用 なに；在某些組合裡也讀 なん，分開教。'),
  W('nihon','日本','にほん','nihon','日本','同一個詞也可讀 にっぽん；第一版固定用 にほん。'),
  W('niku','肉','にく','niku','肉'),
  W('nugu','脱ぐ','ぬぐ','nugu','脫下（鞋子、外套等）','現有口語詞義中已出現；也適合店內試穿情境。'),
  W('nuno','布','ぬの','nuno','布料'),
  W('neru','寝る','ねる','neru','睡覺'),
  W('neko','猫','ねこ','neko','貓','本卡只用一般動物的意思；不沿用其他情境的特殊詞義。'),
  W('norimasu','乗ります','のります','norimasu','搭乘／上車'),
  W('nomu','飲む','のむ','nomu','喝'),
  W('hai','はい','はい','hai','是／好','在此當回應用語；不是助詞 は 的例子。'),
  W('hashi','箸','はし','hashi','筷子','橋也讀 はし；這張只教筷子，第一版不考音調辨義。'),
  W('hidari','左','ひだり','hidari','左邊'),
  W('hitori','一人','ひとり','hitori','一個人／一位'),
  W('fukuro','袋','ふくろ','fukuro','袋子'),
  W('futari','二人','ふたり','futari','兩個人／兩位'),
  W('heya','部屋','へや','heya','房間','單字裡的 へ 讀 he；方向助詞 へ 常讀 e，另列補充。'),
  W('hon','本','ほん','hon','書／書本'),
  W('hontou','本当','ほんとう','hontou','真的'),
  W('matte','待って','まって','matte','等一下'),
  W('mata','また','また','mata','再／又'),
  W('mizu','水','みず','mizu','水'),
  W('migi','右','みぎ','migi','右邊'),
  W('mukou','向こう','むこう','mukou','對面／那一邊'),
  W('muzukashii','難しい','むずかしい','muzukashii','難的'),
  W('me','目','め','me','眼睛'),
  W('mouichido','もう一度','もういちど','mou ichido','再一次'),
  W('motsu','持つ','もつ','motsu','拿／持有'),
  W('yasui','安い','やすい','yasui','便宜的'),
  W('yakitori','焼き鳥','やきとり','yakitori','烤雞肉串'),
  W('yukkuri','ゆっくり','ゆっくり','yukkuri','慢慢地'),
  W('yuugata','夕方','ゆうがた','yuugata','傍晚'),
  W('yoroshiku','よろしく','よろしく','yoroshiku','請多關照','這裡配初次見面情境；完整說法為 よろしくお願いします。'),
  W('yoru','夜','よる','yoru','晚上'),
  W('raishuu','来週','らいしゅう','raishuu','下週'),
  W('rainen','来年','らいねん','rainen','明年'),
  W('ryokou','旅行','りょこう','ryokou','旅行','讀音第一個字是 り，但第一拍是 りょ。可放在 り 的延伸區，不能拿整詞的第一拍當 ri 的聽音題。'),
  W('rikai','理解','りかい','rikai','理解'),
  W('rusu','留守','るす','rusu','不在家／外出中','る 開頭的常用旅遊詞較少，使用這個日常補充詞，不假設已學過。'),
  W('renshuu','練習','れんしゅう','renshuu','練習'),
  W('roku','六','ろく','roku','六'),
  W('wakaru','わかる','わかる','wakaru','懂／了解'),
  W('wakarimashita','わかりました','わかりました','wakarimashita','明白了'),
  W('mizuwo','水をください','みずをください','mizu o kudasai','請給我水','を 是助詞；現代常用發音是 o，用句子教，不找 を 開頭的普通單字。'),
  W('ice','アイス','アイス','aisu','冰淇淋','アイスクリーム 的常用簡稱；依情境也可能指冰的飲品。'),
  W('iyahon','イヤホン','イヤホン','iyahon','耳機'),
  W('internet','インターネット','インターネット','intaanetto','網際網路'),
  W('oolong','ウーロン茶','ウーロンちゃ','uuroncha','烏龍茶'),
  W('aircon','エアコン','エアコン','eakon','冷暖氣機'),
  W('orange','オレンジ','オレンジ','orenji','柳橙／橘色'),
  W('card','カード','カード','kaado','卡片／信用卡','現有 App 是付款情境，該情境譯為信用卡。'),
  W('keyboard','キーボード','キーボード','kiiboodo','鍵盤'),
  W('key','キー','キー','kii','鑰匙／按鍵'),
  W('creditcard','クレジットカード','クレジットカード','kurejitto kaado','信用卡'),
  W('class','クラス','クラス','kurasu','班級／課堂'),
  W('cable','ケーブル','ケーブル','keeburu','電纜／連接線'),
  W('cake','ケーキ','ケーキ','keeki','蛋糕'),
  W('konbini','コンビニ','コンビニ','konbini','便利商店'),
  W('coffee','コーヒー','コーヒー','koohii','咖啡'),
  W('size','サイズ','サイズ','saizu','尺寸'),
  W('salad','サラダ','サラダ','sarada','沙拉'),
  W('seat','シート','シート','shiito','座椅／座位'),
  W('single','シングル','シングル','shinguru','單人的／單人房'),
  W('soup','スープ','スープ','suupu','湯'),
  W('supermarket','スーパー','スーパー','suupaa','超市'),
  W('set','セット','セット','setto','套組／套餐'),
  W('sofa','ソファ','ソファ','sofa','沙發'),
  W('taxi','タクシー','タクシー','takushii','計程車'),
  W('towel','タオル','タオル','taoru','毛巾'),
  W('ticket','チケット','チケット','chiketto','票券'),
  W('cheese','チーズ','チーズ','chiizu','起司'),
  W('tour','ツアー','ツアー','tsuaa','旅行團／旅遊行程'),
  W('tv','テレビ','テレビ','terebi','電視'),
  W('table','テーブル','テーブル','teeburu','桌子'),
  W('toire','トイレ','トイレ','toire','廁所'),
  W('toast','トースト','トースト','toosuto','吐司'),
  W('knife','ナイフ','ナイフ','naifu','刀子／餐刀'),
  W('knit','ニット','ニット','nitto','針織衣物'),
  W('noodle','ヌードル','ヌードル','nuudoru','麵／麵條','ヌ 開頭的旅行詞較少；這是補充詞，也可在 カップヌードル 看見。'),
  W('net','ネット','ネット','netto','網路／網'),
  W('notebook','ノート','ノート','nooto','筆記本'),
  W('hamburger','ハンバーガー','ハンバーガー','hanbaagaa','漢堡'),
  W('heater','ヒーター','ヒーター','hiitaa','暖氣機／加熱器'),
  W('front','フロント','フロント','furonto','飯店櫃台'),
  W('flight','フライト','フライト','furaito','航班／飛行'),
  W('helmet','ヘルメット','ヘルメット','herumetto','安全帽'),
  W('hotel','ホテル','ホテル','hoteru','飯店'),
  W('mask','マスク','マスク','masuku','口罩'),
  W('milk','ミルク','ミルク','miruku','牛奶／奶','例如菜單、咖啡配料會出現；不表示使用者會喝牛奶。'),
  W('ham','ハム','ハム','hamu','火腿','ム 以字中位置教；不為了字首規則硬塞陌生詞。'),
  W('menu','メニュー','メニュー','menyuu','菜單'),
  W('mobile','モバイル','モバイル','mobairu','行動的／手機相關'),
  W('yakult','ヤクルト','ヤクルト','yakuruto','養樂多','產品名稱；作為超市、便利商店可見的補充詞，不假設已學過。'),
  W('uniqlo','ユニクロ','ユニクロ','yunikuro','UNIQLO 服飾店','店名；作為旅行時可見的補充詞，不假設已學過。'),
  W('yogurt','ヨーグルト','ヨーグルト','yooguruto','優格'),
  W('ramen','ラーメン','ラーメン','raamen','拉麵'),
  W('remote','リモコン','リモコン','rimokon','遙控器'),
  W('roomkey','ルームキー','ルームキー','ruumu kii','房間鑰匙'),
  W('receipt','レシート','レシート','reshiito','收據'),
  W('regibag','レジ袋','レジぶくろ','reji bukuro','購物袋','保留常見漢字寫法，讀音中的片假名仍顯示片假名。'),
  W('lobby','ロビー','ロビー','robii','大廳'),
  W('wireless','ワイヤレス','ワイヤレス','waiyaresu','無線的','從現有 ワイヤレスの 取出。'),
  W('wine','ワイン','ワイン','wain','葡萄酒'),
  W('pan','パン','パン','pan','麵包'),
  W('battery','電池','でんち','denchi','電池','屬於 で，不可以把濁音去掉放進 て。第一版收藏庫可存，基本清音表不把它當 て 的字首代表詞。'),
  W('grey','グレー','グレー','guree','灰色','屬於 グ／ぐ；保留在已見過單字庫，濁音練習留待下一版。'),
];

// [key, hiragana, katakana, romaji, row, column, hiragana word IDs, katakana word IDs]
const rows = [
  ['a','あ','ア','a',0,0,['arigatou','asa'],['ice']],
  ['i','い','イ','i',0,1,['ikitai','iie'],['iyahon','internet']],
  ['u','う','ウ','u',0,2,['ue','umi'],['oolong']],
  ['e','え','エ','e',0,3,['eki','eiga'],['aircon']],
  ['o','お','オ','o',0,4,['okaikei','omoi'],['orange']],
  ['ka','か','カ','ka',1,0,['kankou','kaimono'],['card']],
  ['ki','き','キ','ki',1,1,['kippu','kita'],['keyboard','key']],
  ['ku','く','ク','ku',1,2,['kudasai','kutsu'],['creditcard','class']],
  ['ke','け','ケ','ke',1,3,['keitai','kekkou'],['cable','cake']],
  ['ko','こ','コ','ko',1,4,['kore','koko'],['konbini','coffee']],
  ['sa','さ','サ','sa',2,0,['sake','sakana'],['size','salad']],
  ['shi','し','シ','shi',2,1,['shigoto','shio'],['seat','single']],
  ['su','す','ス','su',2,2,['sumimasen','suki'],['soup','supermarket']],
  ['se','せ','セ','se',2,3,['sentakuki','seki'],['set']],
  ['so','そ','ソ','so',2,4,['sore','soto'],['sofa']],
  ['ta','た','タ','ta',3,0,['taiwan','taberu'],['taxi','towel']],
  ['chi','ち','チ','chi',3,1,['chizu','chikatetsu'],['ticket','cheese']],
  ['tsu','つ','ツ','tsu',3,2,['tsugi','tsumetai'],['tour']],
  ['te','て','テ','te',3,3,['te','tenki'],['tv','table']],
  ['to','と','ト','to',3,4,['tomarimasu','tomodachi'],['toire','toast']],
  ['na','な','ナ','na',4,0,['namae','nani'],['knife']],
  ['ni','に','ニ','ni',4,1,['nihon','niku'],['knit']],
  ['nu','ぬ','ヌ','nu',4,2,['nugu','nuno'],['noodle']],
  ['ne','ね','ネ','ne',4,3,['neru','neko'],['net']],
  ['no','の','ノ','no',4,4,['norimasu','nomu'],['notebook']],
  ['ha','は','ハ','ha',5,0,['hai','hashi'],['hamburger']],
  ['hi','ひ','ヒ','hi',5,1,['hidari','hitori'],['heater']],
  ['fu','ふ','フ','fu',5,2,['fukuro','futari'],['front','flight']],
  ['he','へ','ヘ','he',5,3,['heya'],['helmet']],
  ['ho','ほ','ホ','ho',5,4,['hon','hontou'],['hotel']],
  ['ma','ま','マ','ma',6,0,['matte','mata'],['mask']],
  ['mi','み','ミ','mi',6,1,['mizu','migi'],['milk']],
  ['mu','む','ム','mu',6,2,['mukou','muzukashii'],['ham']],
  ['me','め','メ','me',6,3,['me'],['menu']],
  ['mo','も','モ','mo',6,4,['mouichido','motsu'],['mobile']],
  ['ya','や','ヤ','ya',7,0,['yasui','yakitori'],['yakult']],
  ['yu','ゆ','ユ','yu',7,2,['yukkuri','yuugata'],['uniqlo']],
  ['yo','よ','ヨ','yo',7,4,['yoroshiku','yoru'],['yogurt']],
  ['ra','ら','ラ','ra',8,0,['raishuu','rainen'],['ramen']],
  ['ri','り','リ','ri',8,1,['rikai','ryokou'],['remote']],
  ['ru','る','ル','ru',8,2,['rusu'],['roomkey']],
  ['re','れ','レ','re',8,3,['renshuu'],['receipt','regibag']],
  ['ro','ろ','ロ','ro',8,4,['roku'],['lobby']],
  ['wa','わ','ワ','wa',9,0,['wakaru','wakarimashita'],['wireless','wine']],
  ['wo','を','ヲ','o',9,4,['mizuwo'],[]],
  ['n','ん','ン','n',10,0,['hon','nihon'],['pan','konbini']],
];

module.exports = {words, rows};
