// 2026-10-07 expansion: editorial daily/travel vocabulary, with stable explicit IDs.
// The original first two anchors stay first. Extra words are available on demand.
const W = (id, word, reading, romaji, meaningZh, note = '') => ({id, word, reading, romaji, meaningZh, note});
// Each group adds words to the existing curation rather than replacing its IDs.
const hira = {
  a: [W('ame','雨','あめ','ame','雨'), W('ashita','明日','あした','ashita','明天','此處固定用 あした；也有 あす、みょうにち 的讀法。')],
  i: [W('iriguchi','入口','いりぐち','iriguchi','入口'), W('ikura','いくら','いくら','ikura','多少錢','問價格時使用；不是鮭魚卵 イクラ 的詞義。')],
  u: [W('ushiro','後ろ','うしろ','ushiro','後面'), W('ureshii','嬉しい','うれしい','ureshii','高興的')],
  e: [W('eigo','英語','えいご','eigo','英語'), W('en','円','えん','en','日圓','金額單位；整詞也能聽見字尾的 ん。')],
  o: [W('ocha','お茶','おちゃ','ocha','茶'), W('oishii','おいしい','おいしい','oishii','好吃的／好喝的')],
  ka: [W('kasa','傘','かさ','kasa','雨傘'), W('kagi','鍵','かぎ','kagi','鑰匙')],
  ki: [W('kinou','昨日','きのう','kinou','昨天'), W('kirei','きれい','きれい','kirei','漂亮的／乾淨的')],
  ku: [W('kuukou','空港','くうこう','kuukou','機場'), W('kuruma','車','くるま','kuruma','車子')],
  ke: [W('kesa','今朝','けさ','kesa','今天早上'), W('keisatsu','警察','けいさつ','keisatsu','警察')],
  ko: [W('konnichiwa','こんにちは','こんにちは','konnichiwa','你好','問候語最後的 は 讀 wa；第一個字仍是 こ。'), W('kodomo','子供','こども','kodomo','小孩')],
  sa: [W('sakura','桜','さくら','sakura','櫻花'), W('samui','寒い','さむい','samui','寒冷的','通常形容天氣或身體感到冷；物品冰涼用 冷たい。')],
  shi: [W('shiroi','白い','しろい','shiroi','白色的'), W('shashin','写真','しゃしん','shashin','照片','第一個字是 し，第一拍是 しゃ；用來認字，不把整詞開頭當成 shi。')],
  su: [W('sushi','寿司','すし','sushi','壽司'), W('suwaru','座る','すわる','suwaru','坐下')],
  se: [W('sensei','先生','せんせい','sensei','老師／對專業人士的敬稱'), W('semai','狭い','せまい','semai','狹窄的')],
  so: [W('soba','そば','そば','soba','蕎麥麵','這裡是食物；「旁邊」也可說 そば，依情境區分。'), W('soko','そこ','そこ','soko','那裡')],
  ta: [W('takai','高い','たかい','takai','貴的／高的'), W('tanoshii','楽しい','たのしい','tanoshii','開心的／有趣的')],
  chi: [W('chikai','近い','ちかい','chikai','近的'), W('chiisai','小さい','ちいさい','chiisai','小的')],
  tsu: [W('tsukue','机','つくえ','tsukue','桌子'), W('tsukau','使う','つかう','tsukau','使用')],
  te: [W('tenpura','天ぷら','てんぷら','tenpura','天婦羅'), W('tegami','手紙','てがみ','tegami','信件','日文的 手紙 是信件。')],
  to: [W('toukyou','東京','とうきょう','toukyou','東京'), W('tokei','時計','とけい','tokei','時鐘／手錶')],
  na: [W('natsu','夏','なつ','natsu','夏天'), W('nagai','長い','ながい','nagai','長的')],
  ni: [W('nimotsu','荷物','にもつ','nimotsu','行李／物品'), W('nichiyoubi','日曜日','にちようび','nichiyoubi','星期日')],
  nu: [W('nurui','ぬるい','ぬるい','nurui','不冷不熱的／溫溫的'), W('nureru','濡れる','ぬれる','nureru','淋濕／變濕')],
  ne: [W('nedan','値段','ねだん','nedan','價格'), W('nemui','眠い','ねむい','nemui','想睡的')],
  no: [W('norikae','乗り換え','のりかえ','norikae','轉乘／換車'), W('nomimono','飲み物','のみもの','nomimono','飲料')],
  ha: [W('hayai','早い','はやい','hayai','早的','時間早用 早い；速度快的 速い 也讀 はやい。'), W('haru','春','はる','haru','春天')],
  hi: [W('hikouki','飛行機','ひこうき','hikouki','飛機'), W('hiru','昼','ひる','hiru','白天／中午')],
  fu: [W('fuyu','冬','ふゆ','fuyu','冬天'), W('fune','船','ふね','fune','船')],
  he: [W('henji','返事','へんじ','henji','回覆／回答'), W('heta','下手','へた','heta','不擅長的')],
  ho: [W('hoshii','欲しい','ほしい','hoshii','想要的'), W('hokkaidou','北海道','ほっかいどう','hokkaidou','北海道')],
  ma: [W('mae','前','まえ','mae','前面／之前'), W('machi','町','まち','machi','城鎮／街區')],
  mi: [W('mise','店','みせ','mise','店家'), W('miru','見る','みる','miru','看')],
  mu: [W('muryou','無料','むりょう','muryou','免費'), W('murasaki','紫','むらさき','murasaki','紫色')],
  me: [W('megane','眼鏡','めがね','megane','眼鏡'), W('meshi','飯','めし','meshi','飯／餐點','較隨意的說法；禮貌日常可用 ご飯。')],
  mo: [W('momo','桃','もも','momo','桃子'), W('motteiru','持っている','もっている','motte iru','拿著／擁有')],
  ya: [W('yasumi','休み','やすみ','yasumi','休息／休假'), W('yasai','野菜','やさい','yasai','蔬菜')],
  yu: [W('yuubin','郵便','ゆうびん','yuubin','郵件／郵政'), W('yuki','雪','ゆき','yuki','雪')],
  yo: [W('yoyaku','予約','よやく','yoyaku','預約／訂位'), W('yomu','読む','よむ','yomu','讀／閱讀')],
  ra: [W('raigetsu','来月','らいげつ','raigetsu','下個月'), W('rakuna','楽な','らくな','raku na','輕鬆的','楽 是 な 形容詞；修飾名詞時用 楽な。')],
  ri: [W('ringo','りんご','りんご','ringo','蘋果'), W('ryouri','料理','りょうり','ryouri','料理／做菜','第一個字是 り，第一拍是 りょ；認字形與聽 ri 分開。')],
  ru: [W('rusuban','留守番','るすばん','rusuban','看家','る 開頭的常用詞較少；這是 留守 的相關日常詞，不硬湊陌生詞。')],
  re: [W('renraku','連絡','れんらく','renraku','聯絡'), W('reizouko','冷蔵庫','れいぞうこ','reizouko','冰箱')],
  ro: [W('rouka','廊下','ろうか','rouka','走廊'), W('rokugatsu','六月','ろくがつ','rokugatsu','六月')],
  wa: [W('watashi','私','わたし','watashi','我'), W('warui','悪い','わるい','warui','不好的／壞的')],
  wo: [W('korewo','これをください','これをください','kore o kudasai','請給我這個','を 念 o；用整句，不把它教成普通詞的字首。'), W('shashinwo','写真を撮ります','しゃしんをとります','shashin o torimasu','拍照片','目標是句子裡的 を；照片的 しゃ 是另一個組合音。')],
  n: [W('jikan','時間','じかん','jikan','時間'), W('tenin','店員','てんいん',"ten'in",'店員','有兩個 ん；本卡先標出讀音中第一個，整詞一起聽。')],
};
const kata = {
  a: [W('aisukurimu','アイスクリーム','アイスクリーム','aisu kuriimu','冰淇淋'), W('apuri','アプリ','アプリ','apuri','App／應用程式')],
  i: [W('ibento','イベント','イベント','ibento','活動'), W('irasuto','イラスト','イラスト','irasuto','插畫')],
  u: [W('uisukii','ウイスキー','ウイスキー','uisukii','威士忌'), W('uesuto','ウエスト','ウエスト','uesuto','腰圍','衣服尺寸情境的用法。')],
  e: [W('erebeetaa','エレベーター','エレベーター','erebeetaa','電梯'), W('esukareetaa','エスカレーター','エスカレーター','esukareetaa','手扶梯')],
  o: [W('omuraisu','オムライス','オムライス','omuraisu','蛋包飯'), W('oodaa','オーダー','オーダー','oodaa','點餐／訂單')],
  ka: [W('kamera','カメラ','カメラ','kamera','相機'), W('karee','カレー','カレー','karee','咖哩')],
  ki: [W('kyanseru','キャンセル','キャンセル','kyanseru','取消','第一個字是 キ，第一拍是 キャ；不是單獨的 ki。'), W('kyasshuresu','キャッシュレス','キャッシュレス','kyasshuresu','無現金支付','第一個字是 キ，第一拍是 キャ。')],
  ku: [W('kuriimu','クリーム','クリーム','kuriimu','鮮奶油／乳霜','食品或保養品情境會有不同中文意思。'), W('kuriiningu','クリーニング','クリーニング','kuriiningu','洗衣／乾洗')],
  ke: [W('keesu','ケース','ケース','keesu','盒子／保護套'), W('kechappu','ケチャップ','ケチャップ','kechappu','番茄醬')],
  ko: [W('koin','コイン','コイン','koin','硬幣'), W('kopii','コピー','コピー','kopii','影印／複製')],
  sa: [W('sandoicchi','サンドイッチ','サンドイッチ','sandoicchi','三明治'), W('saabisu','サービス','サービス','saabisu','服務','也可能指店家提供的招待或優惠，要看情境。')],
  shi: [W('shawaa','シャワー','シャワー','shawaa','淋浴','第一個字是 シ，第一拍是 シャ。'), W('shanpuu','シャンプー','シャンプー','shanpuu','洗髮精','第一個字是 シ，第一拍是 シャ。')],
  su: [W('sumaho','スマホ','スマホ','sumaho','智慧型手機','スマートフォン 的常用簡稱。'), W('suutsukeesu','スーツケース','スーツケース','suutsu keesu','行李箱')],
  se: [W('seetaa','セーター','セーター','seetaa','毛衣'), W('serufusaabisu','セルフサービス','セルフサービス','serufu saabisu','自助服務')],
  so: [W('soosu','ソース','ソース','soosu','醬汁'), W('sofutokuriimu','ソフトクリーム','ソフトクリーム','sofuto kuriimu','霜淇淋')],
  ta: [W('taipu','タイプ','タイプ','taipu','類型／款式'), W('tankutoppu','タンクトップ','タンクトップ','tanku toppu','無袖背心')],
  chi: [W('chekkuin','チェックイン','チェックイン','chekku in','辦理入住／報到','第一個字是 チ，第一拍是 チェ。'), W('chekkuauto','チェックアウト','チェックアウト','chekku auto','辦理退房','第一個字是 チ，第一拍是 チェ。')],
  tsu: [W('tsuna','ツナ','ツナ','tsuna','鮪魚','菜單或罐頭常見的片假名說法。'), W('tsuin','ツイン','ツイン','tsuin','雙床房','飯店情境指有兩張床的房型。')],
  te: [W('tenisu','テニス','テニス','tenisu','網球'), W('tisshu','ティッシュ','ティッシュ','tisshu','面紙','第一個字是 テ，第一拍是 ティ；不是單獨的 te。')],
  to: [W('tomato','トマト','トマト','tomato','番茄'), W('toreeningu','トレーニング','トレーニング','toreeningu','訓練')],
  na: [W('napukin','ナプキン','ナプキン','napukin','餐巾／衛生棉','餐廳通常是餐巾，藥妝店則可能是衛生棉。'), W('nanbread','ナン','ナン','nan','印度烤餅')],
  ni: [W('nyuusu','ニュース','ニュース','nyuusu','新聞','第一個字是 ニ，第一拍是 ニュ。'), W('ninjin','ニンジン','ニンジン','ninjin','紅蘿蔔','蔬菜名稱常見這種片假名寫法，也可寫 人参。')],
  ne: [W('nekutai','ネクタイ','ネクタイ','nekutai','領帶'), W('neiru','ネイル','ネイル','neiru','美甲／指甲相關')],
  no: [W('nootopasokon','ノートパソコン','ノートパソコン','nooto pasokon','筆記型電腦'), W('nonarukooru','ノンアルコール','ノンアルコール','non arukooru','無酒精','飲品菜單上的用法。')],
  ha: [W('hankachi','ハンカチ','ハンカチ','hankachi','手帕'), W('hangaa','ハンガー','ハンガー','hangaa','衣架')],
  hi: [W('hinto','ヒント','ヒント','hinto','提示'), W('hiiroo','ヒーロー','ヒーロー','hiiroo','英雄')],
  fu: [W('fooku','フォーク','フォーク','fooku','叉子','第一個字是 フ，第一拍是 フォ；不是單獨的 fu。'), W('furaidopoteto','フライドポテト','フライドポテト','furaido poteto','薯條')],
  he: [W('heddohon','ヘッドホン','ヘッドホン','heddohon','頭戴式耳機'), W('headoraiyaa','ヘアドライヤー','ヘアドライヤー','hea doraiyaa','吹風機')],
  ho: [W('hoomu','ホーム','ホーム','hoomu','月台','車站情境；其他情境也有「家／主頁」等意思。'), W('hotto','ホット','ホット','hotto','熱的','飲料菜單上常和 アイス（冰的）對照。')],
  ma: [W('mafuraa','マフラー','マフラー','mafuraa','圍巾'), W('mappu','マップ','マップ','mappu','地圖')],
  mi: [W('mineraruwootaa','ミネラルウォーター','ミネラルウォーター','mineraru wootaa','礦泉水'), W('mini','ミニ','ミニ','mini','迷你／小型的')],
  mu: [W('muubii','ムービー','ムービー','muubii','影片','ム 也有自然的字首例子；原本 ハム 的字中例仍保留。'), W('muudo','ムード','ムード','muudo','氣氛')],
  me: [W('meeru','メール','メール','meeru','電子郵件'), W('memo','メモ','メモ','memo','筆記／備忘錄')],
  mo: [W('moderu','モデル','モデル','moderu','模特兒／機型'), W('monitaa','モニター','モニター','monitaa','螢幕／顯示器')],
  ya: [W('yahoo','ヤフー','ヤフー','yafuu','Yahoo','日本常見的網站與服務名稱；是品牌補充詞。')],
  yu: [W('yunifoomu','ユニフォーム','ユニフォーム','yunifoomu','制服／球衣'), W('yuuro','ユーロ','ユーロ','yuuro','歐元')],
  yo: [W('yoga','ヨガ','ヨガ','yoga','瑜伽'), W('yooroppa','ヨーロッパ','ヨーロッパ','yooroppa','歐洲')],
  ra: [W('rajio','ラジオ','ラジオ','rajio','收音機／廣播'), W('ranchi','ランチ','ランチ','ranchi','午餐','菜單也常用來指午餐套餐。')],
  ri: [W('rippu','リップ','リップ','rippu','唇部用品','商店可能指護唇膏或口紅，要看後面的品名。'), W('riidaa','リーダー','リーダー','riidaa','帶領者／組長')],
  ru: [W('ruuru','ルール','ルール','ruuru','規則'), W('ruuto','ルート','ルート','ruuto','路線')],
  re: [W('resutoran','レストラン','レストラン','resutoran','餐廳'), W('reji','レジ','レジ','reji','收銀台／收銀機')],
  ro: [W('rokkaa','ロッカー','ロッカー','rokkaa','置物櫃'), W('roomaji','ローマ字','ローマじ','roomaji','羅馬拼音')],
  wa: [W('waishatsu','ワイシャツ','ワイシャツ','waishatsu','襯衫'), W('waifai','ワイファイ','ワイファイ','waifai','Wi-Fi／無線網路','也常寫作 Wi-Fi；卡片選用可直接閱讀的片假名寫法。')],
  n: [W('pen','ペン','ペン','pen','筆'), W('botan','ボタン','ボタン','botan','按鈕／鈕扣')],
};
const words = [...Object.values(hira).flat(), ...Object.values(kata).flat()];
const anchors = Object.fromEntries([
  ...Object.entries(hira).map(([id, ws]) => ['hira:' + id, ws.map(w => w.id)]),
  ...Object.entries(kata).map(([id, ws]) => ['kata:' + id, ws.map(w => w.id)]),
]);
module.exports = {words, anchors};
