#!/usr/bin/env node
// 把 assets/sfx/*.mp3（Kenney Interface Sounds，CC0，見 assets/sfx/LICENSE-Kenney-CC0.txt）包成 base64 data URI，
// 輸出 src/sfx.generated.js，由 build.sh 串進第一段 script（index.html 單檔、可離線）。
// 用法：node tools/build-sfx.cjs（build.sh 會自動跑）。沒有任何 mp3 時輸出空物件，App 不出聲但照常運作。
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'assets/sfx');
const map={};let raw=0;
if(fs.existsSync(dir))for(const f of fs.readdirSync(dir).filter(f=>f.endsWith('.mp3')).sort()){
  const b=fs.readFileSync(path.join(dir,f));if(b.length>8000)throw Error('音效太大（>8 KB）：'+f);
  raw+=b.length;map[f.replace(/\.mp3$/,'')]='data:audio/mpeg;base64,'+b.toString('base64');}
const js='// Generated by tools/build-sfx.cjs from assets/sfx/*.mp3 — do not edit.\n// Sounds: Kenney "Interface Sounds" (CC0) — assets/sfx/LICENSE-Kenney-CC0.txt\nvar SFX_DATA = '+JSON.stringify(map)+';\n';
fs.writeFileSync(path.join(root,'src/sfx.generated.js'),js);
console.log(`sfx: ${Object.keys(map).length} clips (${raw} MP3 bytes → ${Buffer.byteLength(js)} bytes JS)`);
