// 由 src/sw.js 產生根目錄 sw.js：VERSION 換成 index.html 的雜湊（index.html 一變，sw.js 就變，瀏覽器會換新版並清舊快取）。
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..');
const v=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'index.html'))).digest('hex').slice(0,12);
const src=fs.readFileSync(path.join(root,'src/sw.js'),'utf8');
if(!src.includes("'__VERSION__'"))throw Error('src/sw.js 缺少 __VERSION__');
fs.writeFileSync(path.join(root,'sw.js'),'// Generated by tools/build-sw.cjs from src/sw.js — do not edit.\n'+src.replace("'__VERSION__'","'"+v+"'"));
new Function(fs.readFileSync(path.join(root,'sw.js'),'utf8'));
console.log('sw.js version',v);
