/* ===== 「把對話走完」：你開口 → 對方自然回答 → 聽懂 → 決定怎麼接 =====
   Each situation has 5 levels. Each level = one full 2-round script.
   r = reply: jp / ro / zh / ch (chunks [jp, 意思]) / easy (simpler restatement used when you say ゆっくり) / q (questions)
   q: {q, o:[correct first, ...], tag, k: chunk index that holds the answer}
   fu = your follow-up: o:[{jp, ro, zh, ok, why}]  */
const LV_NAME = ['', '簡單回答', '自然一點', '多一點資訊', '快速口語', '抓重點'];
const LV_RATE = [0, 0.85, 0.9, 0.95, 1.1, 1.0];
const TAG = {yes:'結論', dir:'方向・路線', place:'地點', num:'數字・時間', reason:'理由', advice:'建議', extra:'多餘的話', fu:'接話'};
const REPAIR = {
  again:{jp:'もう一度お願いします', ro:'Mō ichido onegai shimasu', zh:'請再說一次'},
  slow:{jp:'ゆっくりお願いします', ro:'Yukkuri onegai shimasu', zh:'請說慢一點'},
};

const DLG = [
{id:'train', name:'電車・這班對嗎', place:'JR 大阪站・月台', setup:'你要去京都，眼前停著一班電車。',
 me:{jp:'すみません、この電車は京都に行きますか。', ro:'Sumimasen, kono densha wa Kyōto ni ikimasu ka.', zh:'不好意思，這班電車會到京都嗎？'},
 lv:[null,
 {who:'站務員',
  r1:{jp:'はい、行きます。', ro:'Hai, ikimasu.', zh:'是的，會到。', ch:[['はい','是'],['行きます','會去（會到）']],
    q:[{q:'這班電車會到京都嗎？', o:['會','不會','會，但要換車'], tag:'yes', k:1}]},
  fu:{o:[
    {jp:'京都まで何分くらいですか。', ro:'Kyōto made nanpun kurai desu ka.', zh:'到京都大約幾分鐘？', ok:true, why:'確認了會到，接著問要多久，很自然。'},
    {jp:'京都はどこですか。', ro:'Kyōto wa doko desu ka.', zh:'京都在哪裡？', ok:false, why:'他已經說會到京都了，問「京都在哪裡」對方會聽不懂你想知道什麼。'},
    {jp:'この電車をください。', ro:'Kono densha o kudasai.', zh:'請給我這班電車。', ok:false, why:'ください 是買東西、要東西用的。電車不能「給你」。'}]},
  r2:{jp:'30分くらいです。', ro:'Sanjuppun kurai desu.', zh:'大約 30 分鐘。', ch:[['30分','30 分鐘'],['くらい','大約'],['です','是']],
    q:[{q:'到京都大約要多久？', o:['30 分鐘','13 分鐘','3 分鐘'], tag:'num', k:0}]},
  end:'你搭上這班車，大約 30 分鐘到京都。'},
 {who:'站務員',
  r1:{jp:'はい、行きますよ。京都は四つ目です。', ro:'Hai, ikimasu yo. Kyōto wa yottsu-me desu.', zh:'會喔。京都是第四站。',
    ch:[['はい、行きますよ','會喔（よ＝告訴你一件你不知道的事）'],['京都は','京都呢'],['四つ目です','是第四個（第四站）']],
    q:[{q:'這班電車會到京都嗎？', o:['會','不會','不知道'], tag:'yes', k:0},{q:'京都是第幾站？', o:['第 4 站','第 2 站','第 8 站'], tag:'num', k:2}]},
  fu:{o:[
    {jp:'四つ目ですね。ありがとうございます。', ro:'Yottsu-me desu ne. Arigatō gozaimasu.', zh:'第四站對吧，謝謝。', ok:true, why:'把聽到的重點重複一次＋ね，是最好用的確認方法。'},
    {jp:'京都に行きますか。', ro:'Kyōto ni ikimasu ka.', zh:'會到京都嗎？', ok:false, why:'他剛剛已經回答了，再問一次同樣的問題，對方會以為你沒聽懂。'},
    {jp:'四つですか。いくらですか。', ro:'Yottsu desu ka. Ikura desu ka.', zh:'四個嗎？多少錢？', ok:false, why:'四つ目 是「第四個」，不是「四個東西」；也還沒到問價錢的時候。'}]},
  r2:{jp:'はい、そうです。降りる時は、アナウンスがありますよ。', ro:'Hai, sō desu. Oriru toki wa, anaunsu ga arimasu yo.', zh:'對，沒錯。要下車時會有廣播喔。',
    ch:[['はい、そうです','對，沒錯'],['降りる時は','下車的時候'],['アナウンスがありますよ','會有廣播喔']],
    q:[{q:'他最後多告訴你什麼？', o:['下車時會有廣播','要先買新的票','到下一站要換車'], tag:'extra', k:2}]},
  end:'你搭上了。數到第四站就是京都，車上也會廣播。'},
 {who:'站務員',
  r1:{jp:'はい、行きます。でも、これは各駅停車なので、ちょっと時間がかかりますよ。', ro:'Hai, ikimasu. Demo, kore wa kakueki-teisha na node, chotto jikan ga kakarimasu yo.', zh:'會到。不過這班每站都停，會花一點時間喔。',
    ch:[['はい、行きます','會到'],['でも','不過（後面通常才是重點）'],['これは各駅停車なので','因為這班每站都停（なので＝因為）'],['ちょっと時間がかかりますよ','會花一點時間喔']],
    q:[{q:'這班會到京都嗎？', o:['會，但比較慢','不會','會，而且最快'], tag:'yes', k:1},{q:'為什麼會慢？', o:['每一站都停','路上在施工','要在中途換車'], tag:'reason', k:2}]},
  fu:{o:[
    {jp:'速い電車はありますか。', ro:'Hayai densha wa arimasu ka.', zh:'有比較快的車嗎？', ok:true, why:'聽懂「這班慢」，接著問有沒有快的，對話就往下走了。'},
    {jp:'時間はありますか。', ro:'Jikan wa arimasu ka.', zh:'你有時間嗎？', ok:false, why:'時間がかかる 是「花時間」。時間はありますか 是問對方有沒有空。'},
    {jp:'各駅停車はどこですか。', ro:'Kakueki-teisha wa doko desu ka.', zh:'每站停的車在哪裡？', ok:false, why:'你眼前這班就是各駅停車，不用再找它。'}]},
  r2:{jp:'快速がありますよ。隣の5番線から、10分後に出ます。', ro:'Kaisoku ga arimasu yo. Tonari no go-bansen kara, juppun-go ni demasu.', zh:'有快速車喔。從隔壁的 5 號月台，10 分鐘後發車。',
    ch:[['快速がありますよ','有快速車喔'],['隣の5番線から','從隔壁的 5 號月台（番線＝月台號碼）'],['10分後に出ます','10 分鐘後發車']],
    q:[{q:'快速車在幾號月台？', o:['5 號','9 號','10 號'], tag:'num', k:1},{q:'幾分鐘後發車？', o:['10 分鐘後','5 分鐘後','15 分鐘後'], tag:'num', k:2}]},
  end:'你走到隔壁 5 號月台，搭 10 分鐘後的快速。'},
 {who:'站務員',
  r1:{jp:'あ、京都ですか？これ各駅なんで、次の快速のほうが早いですよ。', ro:'A, Kyōto desu ka? Kore kakueki nan de, tsugi no kaisoku no hō ga hayai desu yo.', zh:'啊，京都嗎？這班是每站停的，下一班快速比較快喔。',
    easy:{jp:'この電車は遅いです。次の快速に乗ってください。', ro:'Kono densha wa osoi desu. Tsugi no kaisoku ni notte kudasai.', zh:'這班車很慢。請搭下一班快速。'},
    ch:[['あ、京都ですか？','啊，京都嗎？（重複你的目的地＝他在確認）'],['これ各駅なんで','這班每站停，所以…（なんで＝なので 的口語，不是「為什麼」）'],['次の快速のほうが','下一班快速比較…（〜のほうが＝比較）'],['早いですよ','快喔']],
    q:[{q:'他建議你怎麼做？', o:['等下一班快速','就搭這班','去別的車站'], tag:'advice', k:2},{q:'這班車怎麼了？', o:['每站停，比較慢','不會到京都','已經客滿'], tag:'reason', k:1}]},
  fu:{o:[
    {jp:'次の快速は何番線ですか。', ro:'Tsugi no kaisoku wa nan-bansen desu ka.', zh:'下一班快速在幾號月台？', ok:true, why:'知道要換快速，下一個要知道的就是在哪裡搭。'},
    {jp:'快速はいくらですか。', ro:'Kaisoku wa ikura desu ka.', zh:'快速要多少錢？', ok:false, why:'JR 的快速通常不用加錢。現在最要緊的是在哪裡搭。'},
    {jp:'各駅はどこですか。', ro:'Kakueki wa doko desu ka.', zh:'每站停的在哪裡？', ok:false, why:'他是叫你「不要搭」各駅，不是叫你去找它。'}]},
  r2:{jp:'同じホームです。この電車が出たら、すぐ来ますよ。', ro:'Onaji hōmu desu. Kono densha ga detara, sugu kimasu yo.', zh:'同一個月台。這班車開走之後，馬上就來了。',
    ch:[['同じホームです','同一個月台'],['この電車が出たら','這班車開走之後（〜たら＝之後）'],['すぐ来ますよ','馬上就來喔']],
    q:[{q:'快速在哪裡搭？', o:['同一個月台','對面的月台','樓下的月台'], tag:'place', k:0},{q:'快速什麼時候來？', o:['這班開走後馬上來','30 分鐘後','1 小時後'], tag:'num', k:1}]},
  end:'你留在同一個月台，等這班開走，搭接著來的快速。'},
 {who:'站務員',
  r1:{jp:'京都でしたら、次の快速に乗ったほうが早いですよ。これは各駅停車なので、京都まで1時間近くかかっちゃいます。快速は5番線から、10時20分発です。', ro:'Kyōto deshitara, tsugi no kaisoku ni notta hō ga hayai desu yo. Kore wa kakueki-teisha na node, Kyōto made ichi-jikan chikaku kakatchaimasu. Kaisoku wa go-bansen kara, jū-ji nijuppun hatsu desu.', zh:'如果是去京都，搭下一班快速比較快喔。這班每站停，到京都要將近一小時。快速是 5 號月台，10 點 20 分發車。',
    easy:{jp:'快速に乗ってください。5番線です。10時20分です。', ro:'Kaisoku ni notte kudasai. Go-bansen desu. Jū-ji nijuppun desu.', zh:'請搭快速。5 號月台。10 點 20 分。'},
    ch:[['京都でしたら','如果是京都的話（でしたら＝如果是）'],['次の快速に乗ったほうが早いですよ','搭下一班快速比較快（〜たほうが＝…比較好）'],['これは各駅停車なので','因為這班每站停'],['京都まで1時間近くかかっちゃいます','到京都要將近一小時（〜ちゃう＝口語，帶「可惜」的語氣）'],['快速は5番線から','快速從 5 號月台'],['10時20分発です','10:20 發車（〜発＝幾點出發）']],
    q:[{q:'你該搭眼前這班嗎？', o:['不要，改搭快速','要，搭這班','不要，去別的車站'], tag:'advice', k:1},{q:'快速在幾號月台？', o:['5 號','2 號','10 號'], tag:'num', k:4},{q:'快速幾點發車？', o:['10:20','10:02','12:20'], tag:'num', k:5}]},
  fu:{o:[
    {jp:'5番線の10時20分ですね。', ro:'Go-bansen no jū-ji nijuppun desu ne.', zh:'5 號月台的 10 點 20 分，對吧？', ok:true, why:'長回答裡只挑「你要行動的資訊」確認一次，最實用。'},
    {jp:'1時間ですか。ありがとうございます。', ro:'Ichi-jikan desu ka. Arigatō gozaimasu.', zh:'一小時嗎？謝謝。', ok:false, why:'一小時是「這班慢車」要花的時間，不是你接下來要做的事。'},
    {jp:'京都でしたら？', ro:'Kyōto deshitara?', zh:'如果是京都的話？', ok:false, why:'でしたら 只是開場的「如果是…」，重複它沒有意義。'}]},
  r2:{jp:'はい、そうです。階段を使って、向かいのホームに行ってください。', ro:'Hai, sō desu. Kaidan o tsukatte, mukai no hōmu ni itte kudasai.', zh:'對。請走樓梯到對面的月台。',
    ch:[['はい、そうです','對'],['階段を使って','走樓梯（使って＝使用）'],['向かいのホームに行ってください','請到對面的月台']],
    q:[{q:'5 號月台怎麼去？', o:['走樓梯到對面月台','就在這個月台','搭電梯到 1 樓'], tag:'dir', k:2}]},
  end:'你走樓梯到對面的 5 號月台，搭 10:20 的快速，比原本快很多。'},
 ]},

{id:'bus', name:'巴士・方向對嗎', place:'京都・巴士站', setup:'你要去金閣寺。站牌前剛好停著一台巴士。',
 me:{jp:'すみません、このバスは金閣寺に行きますか。', ro:'Sumimasen, kono basu wa Kinkakuji ni ikimasu ka.', zh:'不好意思，這台巴士會到金閣寺嗎？'},
 lv:[null,
 {who:'司機',
  r1:{jp:'いいえ、行きません。', ro:'Iie, ikimasen.', zh:'不，不會到。', ch:[['いいえ','不'],['行きません','不會去']],
    q:[{q:'這台會到金閣寺嗎？', o:['不會','會','會，但要換車'], tag:'yes', k:1}]},
  fu:{o:[
    {jp:'金閣寺に行くバスはどこですか。', ro:'Kinkakuji ni iku basu wa doko desu ka.', zh:'去金閣寺的巴士在哪裡？', ok:true, why:'這台不到，就問到的那台在哪裡。'},
    {jp:'じゃあ、乗ります。', ro:'Jā, norimasu.', zh:'那我上車了。', ok:false, why:'他說不會到，上車就坐錯了。'},
    {jp:'金閣寺は好きですか。', ro:'Kinkakuji wa suki desu ka.', zh:'你喜歡金閣寺嗎？', ok:false, why:'這是在聊天，不是在問路。'}]},
  r2:{jp:'向こうのバス停です。', ro:'Mukō no basutei desu.', zh:'在對面的公車站。', ch:[['向こうの','對面的（向こう＝另一邊）'],['バス停です','公車站']],
    q:[{q:'去金閣寺的巴士在哪裡搭？', o:['對面的公車站','這個公車站','車站裡面'], tag:'place', k:0}]},
  end:'你走到對面的公車站。方向對了！'},
 {who:'司機',
  r1:{jp:'いいえ、これは反対方向です。向こう側から乗ってください。', ro:'Iie, kore wa hantai-hōkō desu. Mukō-gawa kara notte kudasai.', zh:'不，這台是反方向。請從對面那一側搭。',
    ch:[['いいえ','不'],['これは反対方向です','這台是反方向（反対＝相反）'],['向こう側から','從對面那一側'],['乗ってください','請搭乘']],
    q:[{q:'這台車怎麼了？', o:['方向相反','已經客滿','今天停駛'], tag:'dir', k:1},{q:'你該去哪裡搭？', o:['對面那一側','同一站等下一班','車站裡面'], tag:'place', k:2}]},
  fu:{o:[
    {jp:'何番のバスですか。', ro:'Nan-ban no basu desu ka.', zh:'是幾號巴士？', ok:true, why:'對面會停很多台，知道號碼才不會又搭錯。'},
    {jp:'反対ですか。じゃあ、乗ります。', ro:'Hantai desu ka. Jā, norimasu.', zh:'反方向嗎？那我上車了。', ok:false, why:'知道是反方向還上車，就會越坐越遠。'},
    {jp:'いくらですか。', ro:'Ikura desu ka.', zh:'多少錢？', ok:false, why:'先確認要搭幾號，價錢之後再問。'}]},
  r2:{jp:'205番か12番ですね。', ro:'Nihyaku-go-ban ka jūni-ban desu ne.', zh:'205 號或 12 號喔。', ch:[['205番か','205 號或…（か＝或）'],['12番ですね','12 號喔']],
    q:[{q:'要搭幾號？', o:['205 或 12','25 或 102','2 或 5'], tag:'num', k:0}]},
  end:'你過馬路到對面，等 205 或 12 號巴士。'},
 {who:'司機',
  r1:{jp:'あ、これは逆方向ですね。金閣寺なら、道を渡って、向こうのバス停から乗ってください。205番です。', ro:'A, kore wa gyaku-hōkō desu ne. Kinkakuji nara, michi o watatte, mukō no basutei kara notte kudasai. Nihyaku-go-ban desu.', zh:'啊，這台是反方向喔。去金閣寺的話，請過馬路，從對面的公車站搭。205 號。',
    ch:[['あ、これは逆方向ですね','啊，這台是反方向（逆＝相反）'],['金閣寺なら','去金閣寺的話（なら＝如果是）'],['道を渡って','過馬路（渡る＝橫越）'],['向こうのバス停から乗ってください','請從對面的公車站搭'],['205番です','205 號']],
    q:[{q:'這台方向對嗎？', o:['反方向','方向對','他沒說'], tag:'dir', k:0},{q:'你要先做什麼？', o:['過馬路','上這台車','走回車站'], tag:'dir', k:2},{q:'要搭幾號？', o:['205','25','250'], tag:'num', k:4}]},
  fu:{o:[
    {jp:'道を渡って、205番ですね。', ro:'Michi o watatte, nihyaku-go-ban desu ne.', zh:'過馬路，205 號，對吧？', ok:true, why:'把「要做的事＋號碼」確認一次，就不會搭錯。'},
    {jp:'この道はどこですか。', ro:'Kono michi wa doko desu ka.', zh:'這條路在哪裡？', ok:false, why:'道を渡って 是「過馬路」，不是要你去找一條路。'},
    {jp:'逆方向に乗ります。', ro:'Gyaku-hōkō ni norimasu.', zh:'我要搭反方向的。', ok:false, why:'逆方向 是他告訴你「這台不對」，不是叫你搭它。'}]},
  r2:{jp:'そうそう。降りる時に、230円払ってくださいね。', ro:'Sō sō. Oriru toki ni, nihyaku-sanjū-en haratte kudasai ne.', zh:'對對。下車時請付 230 圓喔。',
    ch:[['そうそう','對對（口語的「沒錯」）'],['降りる時に','下車的時候'],['230円払ってくださいね','請付 230 圓喔']],
    q:[{q:'什麼時候付錢？付多少？', o:['下車時付 230 圓','上車時付 230 圓','下車時付 320 圓'], tag:'num', k:2}]},
  end:'你過馬路搭 205 號，下車時付 230 圓。'},
 {who:'路人（年輕人）',
  r1:{jp:'え、金閣寺？これ逆っすよ。あっちっす、あっち。道渡ったとこのバス停。', ro:'E, Kinkakuji? Kore gyaku ssu yo. Atchi ssu, atchi. Michi watatta toko no basutei.', zh:'欸，金閣寺？這台是反的啦。那邊、那邊。過了馬路那裡的公車站。',
    easy:{jp:'このバスは反対です。道を渡って、向こうのバス停です。', ro:'Kono basu wa hantai desu. Michi o watatte, mukō no basutei desu.', zh:'這台巴士是反方向。過馬路，在對面的公車站。'},
    ch:[['え、金閣寺？','欸，金閣寺？（重複你的目的地＝在確認）'],['これ逆っすよ','這台是反的啦（っす＝です 的年輕人說法）'],['あっちっす、あっち','那邊、那邊（あっち＝あちら 的口語）'],['道渡ったとこの','過了馬路那裡的（とこ＝ところ）'],['バス停','公車站']],
    q:[{q:'結論是？', o:['這台方向相反','這台會到','金閣寺今天沒開'], tag:'dir', k:1},{q:'他叫你去哪？', o:['過馬路後的公車站','走回車站','就在這裡等'], tag:'place', k:3}]},
  fu:{o:[
    {jp:'すみません、何番のバスに乗ればいいですか。', ro:'Sumimasen, nan-ban no basu ni noreba ii desu ka.', zh:'請問我該搭幾號巴士？', ok:true, why:'對方講得很快，你用自己會的禮貌說法問下一步就好，不用學他的口氣。'},
    {jp:'逆ですか。じゃあ、このバスで大丈夫ですね。', ro:'Gyaku desu ka. Jā, kono basu de daijōbu desu ne.', zh:'反的嗎？那這台就沒問題吧。', ok:false, why:'逆＝相反。他是說這台「不行」。'},
    {jp:'道はどこですか。', ro:'Michi wa doko desu ka.', zh:'路在哪裡？', ok:false, why:'道渡った 是「過了馬路」，路就在你面前。'}]},
  r2:{jp:'えーと、205か、12かな。どっちでも行けますよ。', ro:'Ēto, nihyaku-go ka, jūni ka na. Dotchi demo ikemasu yo.', zh:'嗯…205 或 12 吧。哪一台都可以到喔。',
    ch:[['えーと','嗯…（在想的聲音，不用理它）'],['205か、12かな','205 或 12 吧（かな＝…吧，不太確定的語氣）'],['どっちでも行けますよ','哪一台都能到喔']],
    q:[{q:'要搭哪一號？', o:['205 或 12 都可以','只有 205','只有 12'], tag:'num', k:2}]},
  end:'你過馬路，205 或 12 號哪台先來就搭哪台。'},
 {who:'排隊的阿姨',
  r1:{jp:'金閣寺ですか？このバスも行くことは行くんですけど、すごく遠回りなんですよ。道の向こうから205番に乗ったほうが、20分くらい早く着きます。', ro:'Kinkakuji desu ka? Kono basu mo iku koto wa iku n desu kedo, sugoku tōmawari nan desu yo. Michi no mukō kara nihyaku-go-ban ni notta hō ga, nijuppun kurai hayaku tsukimasu.', zh:'金閣寺嗎？這台到是會到，可是繞很遠的路喔。從馬路對面搭 205 號，大概會早 20 分鐘到。',
    easy:{jp:'このバスは遅いです。向こうで205番に乗ってください。', ro:'Kono basu wa osoi desu. Mukō de nihyaku-go-ban ni notte kudasai.', zh:'這台巴士很慢。請到對面搭 205 號。'},
    ch:[['金閣寺ですか？','金閣寺嗎？（確認你的目的地）'],['このバスも行くことは行くんですけど','這台「到是會到」，但是…（〜ことは〜けど＝雖然是…但）'],['すごく遠回りなんですよ','繞很遠的路（遠回り＝繞遠路）'],['道の向こうから205番に乗ったほうが','從馬路對面搭 205 號的話（〜たほうが＝比較好）'],['20分くらい早く着きます','大約早 20 分鐘到']],
    q:[{q:'這台會到金閣寺嗎？', o:['會，但繞很遠','不會','會，而且最快'], tag:'yes', k:1},{q:'她建議你怎麼做？', o:['到對面搭 205','就搭這台','搭計程車'], tag:'advice', k:3},{q:'可以早多少？', o:['大約 20 分鐘','大約 2 分鐘','大約 2 小時'], tag:'num', k:4}]},
  fu:{o:[
    {jp:'向こうの205番ですね。ありがとうございます。', ro:'Mukō no nihyaku-go-ban desu ne. Arigatō gozaimasu.', zh:'對面的 205 號對吧，謝謝。', ok:true, why:'聽到「行く」不要馬上上車。這題的重點是後面那句建議。'},
    {jp:'行きますね。じゃあ、乗ります。', ro:'Ikimasu ne. Jā, norimasu.', zh:'會到對吧，那我上車。', ok:false, why:'會到，但多花 20 分鐘。けど（但是）後面才是重點。'},
    {jp:'20分ですか。何番ですか。', ro:'Nijuppun desu ka. Nan-ban desu ka.', zh:'20 分鐘嗎？是幾號？', ok:false, why:'她已經說了 205 號，再問一次會讓人覺得你沒在聽。'}]},
  r2:{jp:'はい。信号がすぐそこにあるので、そこで渡ってくださいね。', ro:'Hai. Shingō ga sugu soko ni aru node, soko de watatte kudasai ne.', zh:'對。紅綠燈就在那邊，請在那裡過馬路喔。',
    ch:[['はい','對'],['信号がすぐそこにあるので','紅綠燈就在那邊，所以…（信号＝紅綠燈）'],['そこで渡ってくださいね','請在那裡過馬路喔']],
    q:[{q:'她要你在哪裡過馬路？', o:['旁邊的紅綠燈','地下道','哪裡都可以'], tag:'dir', k:1}]},
  end:'你從旁邊的紅綠燈過馬路，搭 205 號，早 20 分鐘到金閣寺。'},
 ]},

{id:'way', name:'問路・找巴士搭乘處', place:'京都站・出口附近', setup:'你要搭往金閣寺的巴士，但找不到巴士搭乘處。',
 me:{jp:'すみません、バス乗り場はどこですか。', ro:'Sumimasen, basu noriba wa doko desu ka.', zh:'不好意思，巴士搭乘處在哪裡？'},
 lv:[null,
 {who:'站務員',
  r1:{jp:'あそこです。', ro:'Asoko desu.', zh:'在那裡。', ch:[['あそこ','那裡（離你們兩個都遠）'],['です','是']],
    q:[{q:'他怎麼回答？', o:['在那裡（會用手指給你看）','沒有巴士','他不知道'], tag:'place', k:0}]},
  fu:{o:[
    {jp:'あの白い建物ですか。', ro:'Ano shiroi tatemono desu ka.', zh:'是那棟白色的建築嗎？', ok:true, why:'「那裡」太模糊，用看得到的東西確認一次。'},
    {jp:'あそこはどこですか。', ro:'Asoko wa doko desu ka.', zh:'那裡是哪裡？', ok:false, why:'對方會覺得很奇怪。用一個看得到的東西來確認比較好。'},
    {jp:'ありがとうございます。タクシーで行きます。', ro:'Arigatō gozaimasu. Takushī de ikimasu.', zh:'謝謝，我搭計程車去。', ok:false, why:'你是要搭巴士，搭乘處就在那裡，不用放棄。'}]},
  r2:{jp:'はい、あの建物の前です。', ro:'Hai, ano tatemono no mae desu.', zh:'對，在那棟建築前面。', ch:[['はい','對'],['あの建物の','那棟建築的'],['前です','前面']],
    q:[{q:'搭乘處在哪？', o:['那棟建築前面','那棟建築後面','那棟建築裡面'], tag:'place', k:2}]},
  end:'你走到那棟白色建築前面，找到巴士搭乘處。'},
 {who:'站務員',
  r1:{jp:'まっすぐ行って、右です。', ro:'Massugu itte, migi desu.', zh:'直走，然後在右邊。', ch:[['まっすぐ行って','直走'],['右です','在右邊']],
    q:[{q:'怎麼走？', o:['直走，在右邊','直走，在左邊','先右轉再直走'], tag:'dir', k:1}]},
  fu:{o:[
    {jp:'まっすぐ、右ですね。', ro:'Massugu, migi desu ne.', zh:'直走、右邊，對吧？', ok:true, why:'方向最容易聽反，重複一次最保險。'},
    {jp:'左ですか。ありがとうございます。', ro:'Hidari desu ka. Arigatō gozaimasu.', zh:'左邊嗎？謝謝。', ok:false, why:'他說的是 右（みぎ）。左是 ひだり。'},
    {jp:'右はどこですか。', ro:'Migi wa doko desu ka.', zh:'右邊在哪裡？', ok:false, why:'右邊就是右邊，這樣問對方會聽不懂。'}]},
  r2:{jp:'はい。歩いて2分くらいですよ。', ro:'Hai. Aruite ni-fun kurai desu yo.', zh:'對。走路大約 2 分鐘喔。', ch:[['はい','對'],['歩いて','走路'],['2分くらいですよ','大約 2 分鐘喔']],
    q:[{q:'走路多久？', o:['大約 2 分鐘','大約 12 分鐘','大約 20 分鐘'], tag:'num', k:2}]},
  end:'你直走，在右邊找到搭乘處，走 2 分鐘就到了。'},
 {who:'站務員',
  r1:{jp:'この道をまっすぐ行って、二つ目の信号を左に曲がってください。郵便局の隣です。', ro:'Kono michi o massugu itte, futatsu-me no shingō o hidari ni magatte kudasai. Yūbinkyoku no tonari desu.', zh:'這條路直走，在第二個紅綠燈左轉。在郵局隔壁。',
    ch:[['この道をまっすぐ行って','這條路直走'],['二つ目の信号を','在第二個紅綠燈（信号＝紅綠燈）'],['左に曲がってください','請左轉（曲がる＝轉彎）'],['郵便局の隣です','在郵局隔壁']],
    q:[{q:'在哪裡轉？往哪轉？', o:['第二個紅綠燈左轉','第一個紅綠燈右轉','第二個紅綠燈右轉'], tag:'dir', k:2},{q:'旁邊有什麼？', o:['郵局','便利商店','銀行'], tag:'place', k:3}]},
  fu:{o:[
    {jp:'二つ目の信号を左ですね。', ro:'Futatsu-me no shingō o hidari desu ne.', zh:'第二個紅綠燈左轉，對吧？', ok:true, why:'「第幾個＋左右」是最容易聽錯的，確認這兩個就夠了。'},
    {jp:'郵便局はどこですか。', ro:'Yūbinkyoku wa doko desu ka.', zh:'郵局在哪裡？', ok:false, why:'郵局只是用來認路的地標，你不用找它。'},
    {jp:'一つ目ですか。右ですか。', ro:'Hitotsu-me desu ka. Migi desu ka.', zh:'第一個嗎？右轉嗎？', ok:false, why:'兩個都聽反了：是 二つ目（第二個）、左（ひだり）。'}]},
  r2:{jp:'そうです。郵便局の前に、バスの看板が見えますよ。', ro:'Sō desu. Yūbinkyoku no mae ni, basu no kanban ga miemasu yo.', zh:'對。郵局前面可以看到巴士的招牌喔。',
    ch:[['そうです','對'],['郵便局の前に','在郵局前面'],['バスの看板が見えますよ','可以看到巴士的招牌喔（看板＝招牌）']],
    q:[{q:'看到什麼就知道到了？', o:['郵局前的巴士招牌','紅色的大門','車站的時鐘'], tag:'place', k:2}]},
  end:'你在第二個紅綠燈左轉，看到郵局前的巴士招牌就到了。'},
 {who:'站務員',
  r1:{jp:'あー、バス乗り場ですね。そこの階段降りて、地下通って、反対側に出たらすぐですよ。', ro:'Ā, basu noriba desu ne. Soko no kaidan orite, chika tōtte, hantai-gawa ni detara sugu desu yo.', zh:'啊，巴士搭乘處啊。從那邊的樓梯下去，走地下道，到另一側出來就到了喔。',
    easy:{jp:'階段を降りてください。地下を通って、反対側に出てください。', ro:'Kaidan o orite kudasai. Chika o tōtte, hantai-gawa ni dete kudasai.', zh:'請下樓梯。走地下道，從另一側出去。'},
    ch:[['あー、バス乗り場ですね','啊，巴士搭乘處啊（重複＝確認）'],['そこの階段降りて','從那邊的樓梯下去（口語省略了 を）'],['地下通って','走地下道（通る＝經過）'],['反対側に出たら','從另一側出去之後（〜たら＝之後）'],['すぐですよ','馬上就到了喔']],
    q:[{q:'路線順序？', o:['下樓梯→走地下→另一側出去','上樓梯→過天橋→右轉','直走→過馬路→左轉'], tag:'dir', k:1},{q:'出去之後還要走多遠？', o:['馬上就到','10 分鐘','要再搭車'], tag:'place', k:4}]},
  fu:{o:[
    {jp:'反対側の出口は何番ですか。', ro:'Hantai-gawa no deguchi wa nan-ban desu ka.', zh:'另一側的出口是幾號？', ok:true, why:'日本車站出口很多，問出口名稱或號碼最實際。'},
    {jp:'地下鉄に乗りますか。', ro:'Chikatetsu ni norimasu ka.', zh:'要搭地下鐵嗎？', ok:false, why:'地下 是「地下（通道）」，地下鉄 才是地下鐵。他只叫你走過去。'},
    {jp:'階段はいくらですか。', ro:'Kaidan wa ikura desu ka.', zh:'樓梯多少錢？', ok:false, why:'樓梯不用錢。'}]},
  r2:{jp:'出口の番号はないんですけど、「バスのりば」って書いてあるので、それを見ていけば大丈夫です。', ro:'Deguchi no bangō wa nai n desu kedo, "basu noriba" tte kaite aru node, sore o mite ikeba daijōbu desu.', zh:'出口沒有編號，不過有寫「巴士搭乘處」，跟著它走就沒問題。',
    easy:{jp:'「バスのりば」を見てください。', ro:'"Basu noriba" o mite kudasai.', zh:'請看「巴士搭乘處」的標示。'},
    ch:[['出口の番号はないんですけど','出口沒有編號，不過…（けど＝但是，後面才是重點）'],['「バスのりば」って書いてあるので','有寫著「バスのりば」，所以…'],['それを見ていけば大丈夫です','跟著它走就沒問題']],
    q:[{q:'怎麼找到出口？', o:['跟著「バスのりば」的標示','找 3 號出口','再問下一個人'], tag:'place', k:1}]},
  end:'你下樓梯走地下道，跟著「バスのりば」標示，從另一側出來就到了。'},
 {who:'站務員',
  r1:{jp:'バス乗り場は、ここからだとちょっと分かりにくいんですよ。この先の改札を出て、左にずっと行くと、大きいエスカレーターがあるので、それで1階まで降りてください。降りたら目の前です。', ro:'Basu noriba wa, koko kara da to chotto wakarinikui n desu yo. Kono saki no kaisatsu o dete, hidari ni zutto iku to, ōkii esukarētā ga aru node, sore de ikkai made orite kudasai. Oritara me no mae desu.', zh:'巴士搭乘處從這裡過去有點難找喔。從前面的剪票口出去，往左一直走，會有一個大手扶梯，請搭它下到 1 樓。下來就在眼前。',
    easy:{jp:'改札を出て、左です。エスカレーターで1階に降りてください。', ro:'Kaisatsu o dete, hidari desu. Esukarētā de ikkai ni orite kudasai.', zh:'出剪票口，往左。搭手扶梯下到 1 樓。'},
    ch:[['ここからだとちょっと分かりにくいんですよ','從這裡過去有點難找（開場白，不是指路）'],['この先の改札を出て','從前面的剪票口出去（改札＝剪票口）'],['左にずっと行くと','往左一直走的話'],['大きいエスカレーターがあるので','會有大手扶梯，所以…'],['それで1階まで降りてください','搭它下到 1 樓'],['降りたら目の前です','下來就在眼前']],
    q:[{q:'第一句「分かりにくい」是什麼意思？', o:['只是說有點難找','搭乘處今天關閉','要另外付錢'], tag:'extra', k:0},{q:'路線是？', o:['出剪票口→往左→手扶梯下到 1 樓','出剪票口→往右→樓梯上 2 樓','不出剪票口→往左→電梯'], tag:'dir', k:2}]},
  fu:{o:[
    {jp:'改札を出て、左、エスカレーターで1階ですね。', ro:'Kaisatsu o dete, hidari, esukarētā de ikkai desu ne.', zh:'出剪票口、往左、搭手扶梯到 1 樓，對吧？', ok:true, why:'長的指路只挑「動作」確認：出去、往左、往下。'},
    {jp:'分かりにくいですか。じゃあ、いいです。', ro:'Wakarinikui desu ka. Jā, ii desu.', zh:'很難找嗎？那算了。', ok:false, why:'「有點難找」只是開場白，他後面就告訴你怎麼走了。'},
    {jp:'2階ですか。', ro:'Nikai desu ka.', zh:'2 樓嗎？', ok:false, why:'他說的是 1階（いっかい），下到 1 樓。'}]},
  r2:{jp:'そうです、そうです。分からなかったら、また駅員に聞いてくださいね。', ro:'Sō desu, sō desu. Wakaranakattara, mata ekiin ni kiite kudasai ne.', zh:'對對。如果找不到，再問站務員喔。',
    ch:[['そうです、そうです','對對'],['分からなかったら','如果不知道的話'],['また駅員に聞いてくださいね','再問站務員喔（駅員＝站務員）']],
    q:[{q:'他最後說什麼？', o:['找不到就再問站務員','搭計程車比較好','今天沒有巴士'], tag:'extra', k:2}]},
  end:'你出剪票口往左，搭大手扶梯到 1 樓，巴士搭乘處就在眼前。'},
 ]},
];

const DLG_MAP = Object.fromEntries(DLG.map(d => [d.id, d]));

/* Key words to learn BEFORE listening: [日文, 羅馬拼音, 中文] */
const DLG_W = {
  train:[null,
    [['電車','densha','電車'],['行きます','ikimasu','去、會到'],['〜くらい','kurai','大約']],
    [['四つ目','yottsu-me','第四個（第四站）'],['降りる','oriru','下車'],['アナウンス','anaunsu','廣播']],
    [['各駅停車','kakueki-teisha','每站都停的車'],['時間がかかる','jikan ga kakaru','要花時間'],['快速','kaisoku','快速車'],['〜番線','bansen','幾號月台']],
    [['次の','tsugi no','下一個'],['〜のほうが早い','no hō ga hayai','…比較快'],['同じ','onaji','一樣的、同一個'],['ホーム','hōmu','月台']],
    [['〜でしたら','deshitara','如果是…的話'],['〜発','hatsu','幾點發車'],['階段','kaidan','樓梯'],['向かい','mukai','對面']]],
  bus:[null,
    [['バス停','basutei','公車站'],['向こう','mukō','對面、另一邊'],['いいえ','iie','不、不是']],
    [['反対方向','hantai-hōkō','反方向'],['向こう側','mukō-gawa','對面那一側'],['乗ってください','notte kudasai','請搭乘'],['何番','nan-ban','幾號']],
    [['逆方向','gyaku-hōkō','反方向'],['道を渡る','michi o wataru','過馬路'],['払う','harau','付錢'],['降りる時','oriru toki','下車的時候']],
    [['逆','gyaku','相反'],['あっち','atchi','那邊（口語）'],['とこ','toko','地方（ところ 的口語）'],['どっちでも','dotchi demo','哪個都可以']],
    [['遠回り','tōmawari','繞遠路'],['〜けど','kedo','但是（後面才是重點）'],['着きます','tsukimasu','抵達'],['信号','shingō','紅綠燈']]],
  way:[null,
    [['乗り場','noriba','搭乘處'],['あそこ','asoko','那裡'],['建物','tatemono','建築物'],['前','mae','前面']],
    [['まっすぐ','massugu','直走'],['右','migi','右'],['左','hidari','左'],['歩いて','aruite','走路']],
    [['信号','shingō','紅綠燈'],['曲がる','magaru','轉彎'],['二つ目','futatsu-me','第二個'],['郵便局','yūbinkyoku','郵局'],['隣','tonari','隔壁']],
    [['地下','chika','地下（通道）'],['通る','tōru','經過、穿過'],['反対側','hantai-gawa','另一側'],['すぐ','sugu','馬上、很近']],
    [['改札','kaisatsu','剪票口'],['分かりにくい','wakarinikui','不好懂、難找'],['エスカレーター','esukarētā','手扶梯'],['1階','ikkai','一樓'],['目の前','me no mae','眼前'],['駅員','ekiin','站務員']]],
};
