/* ===== English: Claude / AI tool / app interface words =====
   [id, word, 中文, 按下去／看到時代表什麼, category, frequency(1-3), example EN, example 中文, aliases]
   Array order = teaching order (most useful first). */
const CATS = {btn:'按鈕', decide:'決定・權限', file:'檔案', status:'狀態・錯誤', build:'做網站・程式', ai:'AI 工作流程', my:'我貼的'};
const EN_RAW = [
['continue','Continue','繼續','往下一步走，不會取消任何東西','btn',3,'Continue','繼續'],
['cancel','Cancel','取消','放棄這次操作，回到原本畫面；通常不會刪掉東西','btn',3,'Cancel','取消'],
['allow','Allow','允許','給權限：讓 Claude 或網站去做某件事（讀檔案、上網…）','decide',3,'Allow Claude to access this folder?','允許 Claude 存取這個資料夾嗎？',['allowed','allows']],
['deny','Deny','拒絕（不給權限）','Allow 的相反：不讓它做這件事','decide',3,'Allow or deny this request?','允許還是拒絕這個請求？',['denied']],
['approve','Approve','批准','Claude 提出一個動作或修改，你說「可以，照做」','decide',3,'Approve changes','批准這些修改',['approved','approval']],
['save','Save','儲存','把目前內容存起來，關掉後還在','btn',3,'Save changes','儲存修改',['saved']],
['send','Send','傳送','把訊息送出去給對方（或給 Claude）','btn',3,'Send message','傳送訊息',['sent']],
['retry','Retry','重試','剛剛失敗了，再做一次同一件事','status',3,'Failed to load. Retry','載入失敗。重試'],
['confirm','Confirm','確認','再確定一次你真的要做（常在危險動作前）','decide',3,'Confirm delete','確認刪除',['confirmation','confirmed']],
['accept','Accept','接受','同意一份條款、建議或邀請','decide',3,'Accept all','全部接受',['accepted']],
['stop','Stop','停止','讓正在進行的事停下來','btn',3,'Stop generating','停止產生回答',['stopped']],
['delete','Delete','刪除','刪除指定的東西；能否復原要看這個功能的說明，不是字本身的保證','btn',3,'Delete chat','刪除對話',['deleted','deleting']],
['edit','Edit','編輯','修改內容','btn',3,'Edit message','編輯訊息',['edited','editing']],
['copy','Copy','複製','先複製起來，等一下可以貼上','btn',3,'Copy code','複製程式碼',['copied']],
['done','Done','完成','做好了、結束這個步驟','btn',3,'Done','完成'],
['error','Error','錯誤','出問題了','status',3,'An error occurred','發生錯誤',['errors']],
['failed','Failed','失敗','那件事沒有成功','status',3,'Upload failed','上傳失敗',['fail','failure']],
['wrong','Something went wrong','出了點問題','最常見的錯誤訊息，多半重試就好','status',3,'Something went wrong. Please try again.','出了點問題，請再試一次。'],
['tryagain','Try again','再試一次','和 Retry 一樣：再做一次剛剛失敗的事','status',3,'Please try again later','請稍後再試'],
['submit','Submit','提交','把填好的表單正式交出去','btn',2,'Submit feedback','提交意見回饋',['submitted']],
['apply','Apply','套用','讓剛剛改的設定「現在生效」','btn',2,'Apply changes','套用修改',['applied']],
['upload','Upload','上傳','把你手機／電腦裡的檔案送上去','file',3,'Upload a file','上傳檔案',['uploaded','uploading']],
['download','Download','下載','把檔案存到你的手機／電腦','file',3,'Download file','下載檔案',['downloaded']],
['attach','Attach','附加','把檔案夾在訊息裡一起送','file',3,'Attach files','附加檔案',['attachment','attachments','attached']],
['file','File','檔案','一份文件、圖片、程式…','file',3,'Choose a file','選擇一個檔案',['files']],
['folder','Folder','資料夾','裝檔案的地方','file',3,'Open folder','開啟資料夾',['folders','directory']],
['permission','Permission','權限','「可以做某件事」的許可','decide',3,'Permission required','需要權限',['permissions']],
['always','Always allow','永遠允許','以後同樣的事都不用再問你','decide',3,'Always allow','永遠允許'],
['once','Allow once','只允許這一次','這次可以，下次還會再問你','decide',3,'Allow once','只允許這一次'],
['settings','Settings','設定','調整 App 怎麼運作的地方','btn',3,'Open settings','打開設定',['setting']],
['enable','Enable','啟用（打開功能）','把一個功能打開','decide',3,'Enable web search','啟用網路搜尋',['enabled']],
['disable','Disable','停用（關掉功能）','把一個功能關掉','decide',2,'Disable notifications','停用通知',['disabled']],
['close','Close','關閉','把這個視窗／面板關掉','btn',3,'Close','關閉',['closed']],
['open','Open','開啟','打開','btn',3,'Open in new tab','在新分頁開啟',['opened']],
['back','Back','返回','回到上一頁','btn',3,'Go back','返回上一頁'],
['next','Next','下一步','前往下一個步驟','btn',3,'Next','下一步'],
['refresh','Refresh','重新整理','重新載入整個畫面，看最新狀態','status',2,'Refresh the page','重新整理頁面',['reload']],
['undo','Undo','復原（上一步）','取消你剛剛做的那一步','btn',2,'Undo','復原'],
['discard','Discard','捨棄','丟掉還沒儲存的內容','btn',2,'Discard changes?','要捨棄修改嗎？'],
['keep','Keep','保留','留著、不要丟','btn',2,'Keep changes','保留修改'],
['replace','Replace','取代','用新的蓋掉舊的','btn',2,'Replace existing file?','要取代現有的檔案嗎？',['overwrite','replaced']],
['remove','Remove','移除','從這裡拿掉，但東西本身可能還在','btn',2,'Remove attachment','移除附件',['removed']],
['sure','Are you sure?','你確定嗎？','做危險動作前的最後確認','decide',3,'Are you sure you want to delete this?','你確定要刪除這個嗎？'],
['cantundo',"can't be undone",'無法復原','按下去就回不來了，小心','decide',3,"This action can't be undone.",'這個動作無法復原。',['cannot be undone']],
['review','Review','檢查（審閱）','先看過一遍再決定','decide',2,'Review changes','檢查修改內容',['reviewed']],
['reject','Reject','駁回（不接受）','不接受這個修改或提案','decide',2,'Reject changes','不接受這些修改',['rejected']],
['decline','Decline','婉拒','客氣地說不要（邀請、條款）','decide',2,'Decline','婉拒',['declined']],
['skip','Skip','跳過','這一步先不做','btn',2,'Skip for now','先跳過'],
['proceed','Proceed','繼續進行','和 Continue 很像，常出現在警告之後','decide',2,'Proceed anyway?','還是要繼續嗎？'],
['required','Required','必填（必要）','一定要有，不然不能繼續','decide',2,'This field is required','這一欄必填',['require','requires']],
['optional','Optional','可選','可做可不做','decide',2,'Optional','可不填'],
['loading','Loading','載入中','正在讀取，請等一下','status',3,'Loading…','載入中…',['load']],
['processing','Processing','處理中','正在處理你的要求','status',2,'Processing your file','正在處理你的檔案',['process']],
['waiting','Waiting','等待中','在等某件事——常常是在等「你」','status',2,'Waiting for approval','等待你的批准',['wait']],
['pending','Pending','待處理','還沒完成、正在排隊','status',2,'Pending','待處理'],
['search','Search','搜尋','找東西','btn',3,'Search chats','搜尋對話',['searching']],
['select','Select','選擇','點選其中一個（或多個）','btn',3,'Select all','全選',['selected']],
['paste','Paste','貼上','把複製的內容放進來','btn',2,'Paste text here','把文字貼在這裡',['pasted']],
['create','Create','建立','從無到有做出一個新東西','btn',3,'Create project','建立專案',['created']],
['new','New','新的','新開一個','btn',3,'New chat','新對話'],
['add','Add','加入（新增）','把東西加進來','btn',3,'Add to project','加到專案裡',['added']],
['connect','Connect','連接','把兩個東西接起來（帳號、工具）','ai',3,'Connect Google Drive','連接 Google 雲端硬碟',['connected']],
['connection','Connection','連線','網路或服務之間的連接','status',2,'Connection lost','連線中斷'],
['network','Network','網路','上網的連線','status',2,'Network error','網路錯誤'],
['offline','Offline','離線','沒有網路','status',2,"You're offline",'你目前離線'],
['limit','Limit','上限（限制）','已經用到上限了','status',3,"You've reached your usage limit",'你已經達到使用上限',['limits','rate limit','limited']],
['update','Update','更新','改成最新狀態（通常免費）','build',3,'Update available','有新的更新',['updated','updating']],
['upgrade','Upgrade','升級','換成更高級的方案或版本（常要付錢）','ai',2,'Upgrade plan','升級方案'],
['view','View','查看','看內容（不修改）','btn',3,'View details','查看詳細內容'],
['preview','Preview','預覽','正式用之前先看看長怎樣','build',2,'Preview','預覽'],
['show','Show more','顯示更多','展開看更多內容','btn',2,'Show more','顯示更多'],
['learnmore','Learn more','了解更多','點進去看說明','btn',2,'Learn more','了解更多'],
['expand','Expand','展開','打開看完整內容；相反操作是 Collapse（收合）','btn',1,'Expand details','展開詳細內容',['expanded','expanding']],
['collapse','Collapse','收合','把展開的內容收起來；內容仍在，並未刪除','btn',1,'Collapse details','收合詳細內容',['collapsed','collapsing']],
['run','Run','執行','讓程式或指令開始跑','build',3,'Run command','執行指令',['running','ran']],
['code','Code','程式碼','寫給電腦看的指令','build',3,'Copy code','複製程式碼'],
['command','Command','指令','叫電腦做事的一行文字','build',2,'Run this command?','要執行這個指令嗎？',['commands']],
['changes','Changes','修改內容','被改過的地方','build',3,'3 changes','3 處修改',['change','changed']],
['build','Build','建置','把程式組裝成可以用的成品','build',2,'Build failed','建置失敗',['building','built']],
['deploy','Deploy','部署','把網站或程式放到伺服器上，讓別人能用','build',2,'Deploy to production','部署到正式環境',['deployed','deployment']],
['publish','Publish','發布','公開出去，讓別人看得到','build',2,'Publish','發布',['published']],
['version','Version','版本','同一個東西的第幾版','build',2,'Version 2','第 2 版',['versions']],
['install','Install','安裝','把程式裝到裝置上','build',2,'Install package','安裝套件',['installed','installing']],
['fix','Fix','修正','把問題修好','build',2,'Fix this error','修正這個錯誤',['fixed']],
['test','Test','測試','試試看能不能正常運作','build',2,'Run tests','執行測試',['tests','testing']],
['execute','Execute','執行（正式說法）','和 Run 一樣，比較正式','build',1,'Execute code','執行程式碼'],
['browser','Browser','瀏覽器','上網的 App（Safari、Chrome）','build',2,'Open in browser','用瀏覽器開啟'],
['link','Link','連結','點了會開網頁的網址','btn',3,'Copy link','複製連結',['links']],
['share','Share','分享','給別人看','btn',3,'Share chat','分享對話',['shared']],
['export','Export','匯出','把資料轉存成檔案帶出去','file',2,'Export data','匯出資料'],
['import','Import','匯入','把外面的資料帶進來','file',2,'Import','匯入'],
['rename','Rename','重新命名','改名字','file',2,'Rename','重新命名'],
['move','Move','移動','換位置','file',2,'Move to folder','移到資料夾'],
['clear','Clear','清除','把內容清空','btn',2,'Clear all','全部清除',['cleared']],
['reset','Reset','重設','回到最初的預設狀態','btn',2,'Reset to default','重設為預設值'],
['revert','Revert','還原（回到舊版本）','回到之前某個版本','build',1,'Revert to previous version','還原到上一個版本'],
['dismiss','Dismiss','關掉提示','把通知或提示關掉，不處理','btn',2,'Dismiss','關掉提示'],
['gotit','Got it','知道了','表示「我看懂了」，把提示關掉','btn',2,'Got it','知道了'],
['signin','Sign in','登入','進入你的帳號','btn',2,'Sign in to continue','登入以繼續',['log in','login','sign-in']],
['logout','Log out','登出','離開你的帳號','btn',2,'Log out','登出',['sign out','logout']],
['success','Success','成功','做好了','status',2,'Success!','成功！',['successful','successfully']],
['complete','Complete','完成的','已經全部做完','status',2,'Task complete','任務完成',['completed']],
['inprogress','In progress','進行中','正在做，還沒好','status',2,'In progress','進行中'],
['timeout','Timed out','逾時','等太久，系統放棄了','status',2,'Request timed out','請求逾時',['timeout','time out']],
['invalid','Invalid','無效的','格式錯了或不被接受','status',2,'Invalid file type','無效的檔案類型'],
['notfound','Not found','找不到','東西不存在或已被刪掉','status',2,'File not found','找不到檔案'],
['unavailable','Unavailable','無法使用','暫時不能用','status',2,'Service unavailable','服務暫時無法使用'],
['unable','Unable to','無法…','後面接「做不到的那件事」','status',2,'Unable to load file','無法載入檔案'],
['expired','Expired','已過期','時間到了，失效了','status',1,'Session expired','登入已過期',['expire']],
['generate','Generate','產生','讓 AI 做出內容','ai',3,'Generating…','正在產生…',['generating','generated']],
['regenerate','Regenerate','重新產生','同一個問題，請 AI 再回答一次','ai',2,'Regenerate response','重新產生回應'],
['chat','Chat','對話','一整串聊天','ai',3,'New chat','新對話',['chats','conversation']],
['prompt','Prompt','提示詞','你打給 AI 的指令或問題','ai',2,'Write a prompt','寫一段提示詞',['prompts']],
['response','Response','回應','AI 回覆你的內容','ai',2,'Copy response','複製回應',['responses','reply']],
['project','Project','專案','一組相關的對話和檔案','ai',2,'Add to project','加入專案',['projects']],
['model','Model','模型','哪一個 AI（例如 Opus、Sonnet）','ai',2,'Choose model','選擇模型',['models']],
['usage','Usage','用量','你用了多少額度','ai',2,'Usage limit','用量上限'],
['memory','Memory','記憶','Claude 記得你的資料','ai',2,'Memory updated','記憶已更新'],
['thinking','Thinking','思考中','AI 正在想，還沒回答','ai',2,'Thinking…','思考中…',['think']],
['task','Task','任務','一件要做的工作','ai',2,'Task running','任務進行中',['tasks']],
['tool','Tool','工具','AI 可以用的功能（搜尋、讀檔案…）','ai',2,'Tool use','使用工具',['tools']],
['draft','Draft','草稿','還沒完成的版本','ai',2,'Save draft','儲存草稿',['drafts']],
['request','Request','請求','向系統或伺服器「要」某樣東西','status',2,'Request failed','請求失敗',['requests','requested']],
['access','Access','存取（使用權）','能不能打開或使用','decide',2,'Request access','請求存取權限'],
['trust','Trust','信任','相信這個來源是安全的','decide',1,'Do you trust this folder?','你信任這個資料夾嗎？',['trusted']],
];

/* Look-alike groups: the heart of the English mode.
   rule = how to tell them apart; roles = one line per word; sc = realistic situations → correct word */
const GROUPS = {
  agree:{t:'同意類', ids:['allow','approve','accept','confirm'],
    rule:'先問「它在要什麼？」要權限 → Allow；要你點頭讓它照做、改東西 → Approve；給你條款或建議 → Accept；問你「確定嗎？」→ Confirm。',
    roles:{allow:'給權限，讓它能做',approve:'批准它提出的動作或修改',accept:'接受條款、建議、邀請',confirm:'再確定一次（危險動作前）'},
    sc:[['Claude 想讀取你電腦裡的一個資料夾，先問你可不可以','allow'],['Claude 改好了網站程式，等你點頭讓修改生效','approve'],['網站跳出「使用條款」要你同意','accept'],['你按了刪除，它又跳出「你確定嗎？」','confirm']]},
  no:{t:'拒絕類', ids:['deny','reject','decline','cancel'],
    rule:'每個「不要」都對應一個「要」：Deny ↔ Allow（權限）、Reject ↔ Approve（修改）、Decline ↔ Accept（邀請、條款）；Cancel 是整個操作都不做了。',
    roles:{deny:'不給權限（Allow 的相反）',reject:'不接受修改（Approve 的相反）',decline:'婉拒邀請、條款（Accept 的相反）',cancel:'整個動作取消，回到原本'},
    sc:[['Claude 想存取你的相機，你不想給','deny'],['Claude 改了程式，你看了覺得不對，不要這些修改','reject'],['有人邀請你加入專案，你不想加入','decline'],['你打開了「分享」視窗，後來決定不分享了','cancel']]},
  enable:{t:'Allow vs Enable', ids:['allow','enable','disable'],
    rule:'Allow 是讓「某個人或程式」做事（給權限）；Enable 是把「某個功能」打開（開關）。Disable 是把功能關掉。',
    roles:{allow:'讓它做（對象是人或程式）',enable:'打開功能（對象是開關）',disable:'關掉功能'},
    sc:[['設定裡要把「網路搜尋」這個功能打開','enable'],['Claude 要求使用你的檔案，你同意','allow'],['想把通知功能關掉','disable']]},
  once:{t:'Always allow vs Allow once', ids:['always','once'],
    rule:'Allow once 只放行這一次，下次還會問；Always allow 以後同類的事都不再問。沒把握時選 Allow once。',
    roles:{always:'以後都不問',once:'只有這一次'},
    sc:[['你只想讓 Claude 這次執行這個指令，下次再問你','once'],['同一種動作你很放心，以後不想再被問','always']]},
  send:{t:'Send vs Submit', ids:['send','submit'],
    rule:'Send 是把訊息傳給人或 AI；Submit 是把「表單、答案」正式交出去。',
    roles:{send:'傳訊息',submit:'交表單、交答案'},
    sc:[['打好給 Claude 的訊息，要傳出去','send'],['填完意見回饋表單，要正式交出','submit']]},
  save:{t:'Save vs Apply vs Keep', ids:['save','apply','keep'],
    rule:'Save 把內容存起來（關掉後還在）；Apply 讓改好的設定「現在生效」；Keep 是「保留，不要丟」。',
    roles:{save:'存起來',apply:'讓設定現在生效',keep:'保留不丟'},
    sc:[['改了字體大小的設定，想馬上看到效果','apply'],['寫好一份文件，要存起來明天繼續','save'],['它問你修改要保留還是捨棄，你要留著','keep']]},
  cancel:{t:'Cancel vs Discard vs Stop', ids:['cancel','discard','stop'],
    rule:'Cancel 取消這次操作、回到原本；Discard 丟掉「還沒存的修改」；Stop 讓「正在跑」的事停下來。',
    roles:{cancel:'不做了，回到原本',discard:'丟掉沒存的修改',stop:'讓正在跑的停下'},
    sc:[['Claude 正在寫很長的回答，你想讓它停','stop'],['你改了一半不想要了，要丟掉沒存的修改','discard'],['跳出一個刪除視窗，你決定不刪了、回到原本畫面','cancel']]},
  retry:{t:'Retry vs Refresh', ids:['retry','tryagain','refresh'],
    rule:'Retry = Try again：再做一次剛剛失敗的那件事；Refresh：把整個畫面重新載入。',
    roles:{retry:'再做一次失敗的事',tryagain:'同 Retry（多出現在句子裡）',refresh:'重新載入整個畫面'},
    sc:[['上傳失敗，想再傳一次同一個檔案','retry'],['畫面好像卡住沒更新，想重新載入頁面','refresh']]},
  delete:{t:'Delete vs Remove vs Clear', ids:['delete','remove','clear'],
    rule:'Delete：刪除指定的東西，是否能復原要看說明；Remove：從「這裡」拿掉，原本的可能還在；Clear：把內容清空。動手前一起看受詞與確認訊息。',
    roles:{delete:'刪除指定的東西',remove:'從這裡拿掉',clear:'把內容清空'},
    sc:[['把附件從這則訊息拿掉，但檔案本身還在你手機','remove'],['把整個對話永久刪除','delete'],['把搜尋框裡的字全部清空','clear']]},
  next:{t:'往前走的按鈕', ids:['continue','next','proceed','done','back','skip'],
    rule:'Continue／Next 往前；Proceed 多在警告後出現（還是要繼續）；Done 全部結束；Back 回上一步；Skip 這步不做。',
    roles:{continue:'繼續',next:'下一步',proceed:'警告後仍要繼續',done:'全部完成',back:'回上一步',skip:'這步跳過'},
    sc:[['設定第 2 步做完了，要去第 3 步','next'],['全部設定都完成了','done'],['跳出警告，但你還是要做','proceed'],['想回上一頁改東西','back'],['這一步先不填','skip']]},
  closeg:{t:'Close vs Dismiss vs Got it', ids:['close','dismiss','gotit'],
    rule:'Close 關掉視窗；Dismiss 關掉提示、不處理它；Got it 是「我看懂了」再關掉。這些字通常不是刪除指令；關閉編輯視窗時，仍要看未儲存內容的提醒。',
    roles:{close:'關視窗',dismiss:'關提示、不處理',gotit:'我懂了，關掉'},
    sc:[['新功能介紹看完了，要表示「懂了」','gotit'],['想把整個設定視窗關掉','close']]},
  updown:{t:'上傳・下載・附加', ids:['upload','download','attach','export','import'],
    rule:'方向最重要：Upload 送上去（你的裝置 → 雲端）；Download 拿下來（雲端 → 你的裝置）；Attach 夾在訊息裡；Export 帶出去；Import 帶進來。',
    roles:{upload:'你的裝置 → 上去',download:'上面 → 你的裝置',attach:'夾在訊息裡',export:'資料帶出去',import:'資料帶進來'},
    sc:[['把手機裡的照片給 Claude 看','upload'],['把 Claude 做好的檔案存到手機','download'],['把 PDF 夾在這則訊息一起送','attach']]},
  updg:{t:'Update vs Upgrade', ids:['update','upgrade'],
    rule:'Update 更新成最新（通常免費）；Upgrade 升級成更高級（常要付費）。',
    roles:{update:'變成最新',upgrade:'變成更高級（常付費）'},
    sc:[['App 有新版本，修了一些問題','update'],['想換成更貴、額度更多的方案','upgrade']]},
  view:{t:'查看、展開與收合', ids:['view','preview','show','learnmore','expand','collapse'],
    rule:'View 查看；Preview 先看效果；Show more／Expand 展開更多；Collapse 把內容收合；Learn more 打開說明。Expand 與 Collapse 是相反操作。',
    roles:{view:'查看',preview:'先看效果',show:'顯示更多',learnmore:'看說明',expand:'展開',collapse:'收合'},
    sc:[['Claude 做好網站，想在發布前先看看長怎樣','preview'],['想看這個錯誤的說明文章','learnmore'],['已經展開的詳細內容，想先收起來','collapse'],['目前只看到摘要，想展開詳細內容','expand']]},
  runG:{t:'Run vs Execute vs Build', ids:['run','execute','build','command'],
    rule:'Run 和 Execute 都是「執行」（Execute 比較正式）；Build 是把程式組裝成成品；Command 是那一行「指令」本身。',
    roles:{run:'執行',execute:'執行（正式）',build:'組裝成成品',command:'指令本身（名詞）'},
    sc:[['Claude 問你能不能讓它跑這一行指令','run'],['程式要先組裝好才能發布','build']]},
  pub:{t:'Publish vs Deploy', ids:['publish','deploy'],
    rule:'Publish 是「公開，讓人看得到」；Deploy 是「把程式放到伺服器上運作」。做網站時兩個常一起出現。',
    roles:{publish:'公開出去',deploy:'放上伺服器運作'},
    sc:[['把寫好的文章公開給大家看','publish'],['把網站程式放上伺服器','deploy']]},
  undoG:{t:'Undo vs Revert vs Reset', ids:['undo','revert','reset'],
    rule:'Undo 退回「上一步」；Revert 回到「之前某個版本」；Reset 回到「最初的預設值」。',
    roles:{undo:'退回上一步',revert:'回到舊版本',reset:'回到預設值'},
    sc:[['剛剛不小心刪了一段字，想退回一步','undo'],['設定亂掉了，想全部回到原廠預設','reset'],['網站改壞了，想回到昨天那個版本','revert']]},
  addG:{t:'Create vs New vs Add', ids:['create','new','add'],
    rule:'Create 從無到有做出來；New 開一個新的；Add 把東西加進「已經存在的地方」。',
    roles:{create:'做出新東西',new:'開一個新的',add:'加進去'},
    sc:[['把一個檔案放進現有的專案裡','add'],['開一個全新的對話','new']]},
  wait:{t:'「請等一下」系列', ids:['loading','processing','pending','waiting','thinking','inprogress'],
    rule:'都代表「還沒好」。特別注意 Waiting：常常是在等「你」按按鈕（Waiting for approval）。',
    roles:{loading:'讀取中',processing:'處理中',pending:'排隊待處理',waiting:'在等（常是等你）',thinking:'AI 在想',inprogress:'進行中'},
    sc:[['畫面寫著 Claude 在等你批准才能繼續','waiting'],['Claude 還在想答案','thinking']]},
  copyG:{t:'Copy vs Paste', ids:['copy','paste'],
    rule:'Copy 先複製；Paste 再貼上。順序永遠是 Copy → Paste。',
    roles:{copy:'複製（先）',paste:'貼上（後）'},
    sc:[['想把 Claude 給的程式碼拿走','copy'],['要把剛剛複製的文字放進輸入框','paste']]},
  gen:{t:'Generate vs Regenerate', ids:['generate','regenerate'],
    rule:'re- 開頭 = 再一次。Generate 產生；Regenerate 重新產生一次（同一個問題換個回答）。',
    roles:{generate:'產生',regenerate:'再產生一次'},
    sc:[['不滿意這個回答，想請 AI 用同一個問題再回答一次','regenerate']]},
  conn:{t:'連線系列', ids:['connect','connection','network','offline'],
    rule:'Connect 是動作（去連接）；Connection／Network 是名詞（連線、網路）；Offline 是沒網路。看到 Connection lost / Offline 先檢查網路。',
    roles:{connect:'去連接（動作）',connection:'連線（名詞）',network:'網路',offline:'沒網路'},
    sc:[['想把 Google 雲端硬碟接到 Claude','connect']]},
};

/* Very common function words: never pushed into review */
const STOP = new Set(('a an the to of and or in on at for with by from as is are was were be been being am it its this that these those you your yours we our us i me my he she they them their his her not no yes do does did have has had if then than so but all any some more most other such only just also very too here there what which who whom when where why how about into out up down over again please can could will would should may might must shall let lets get got make made one two three new file s t ll re ve d m ok okay hi hello thanks thank sorry via per etc now use using used want need needs like see seem seems also into onto off yet still even each every both either neither own same few many much well back way time day').split(' '));

/* names, file types and tech tokens: not vocabulary to learn */
const NAMES = new Set('claude anthropic google drive github gitlab chrome safari firefox iphone ipad ios mac macos windows linux android gmail slack notion figma openai chatgpt gpt sonnet opus haiku fable mythos api url urls http https www com org pdf png jpg jpeg gif svg html css js ts json csv txt md npm pip node python javascript typescript react vercel netlify id ids ui'.split(' '));
